import type {
  CaseStudy,
  CommandEntry,
  Comparison,
  DictEntry,
  EquationEntry,
  Flashcard,
  GraphEdge,
  GraphNode,
  Mistake,
  SoftwareLab,
  VivaQuestion,
} from "@/lib/academy/types";
import type { L10n } from "@/lib/academy/types";
import { L } from "./helpers";

export const flashcards: Flashcard[] = [
  { id: "fc1", deck: "thermo", front: L("ΔG = ؟", "ΔG = ?"), back: L("ΔH − TΔS. إشارة سالبة تفضّل الارتباط عند المعيار.", "ΔH − TΔS. Negative favours binding at the standard state."), tags: ["thermo"] },
  { id: "fc2", deck: "docking", front: L("هل درجة Vina هي ΔG؟", "Is a Vina score ΔG?"), back: L("لا. مرتِّب تقريبي لهيئات.", "No. An approximate pose ranker."), tags: ["docking"] },
  { id: "fc3", deck: "md", front: L("RMSD مسطح يعني تقارب؟", "Flat RMSD means converged?"), back: L("لا. قد تكون بئراً ضيقة أو معاينة ناقصة. تحتاج نُسخاً ومشاهدات أخرى.", "No. May be a narrow well or thin sampling. Need replicas and other observables."), tags: ["md"] },
  { id: "fc4", deck: "ff", front: L("ما حدود الرابط التوافقي في MM؟", "Limit of a harmonic bond in MM?"), back: L("لا يكسر الرابطة. لا تفاعل تساهمي.", "It cannot break. No covalent chemistry."), tags: ["mechanics"] },
  { id: "fc5", deck: "lj", front: L("ماذا يفعل r⁻¹² في لينارد-جونز؟", "What does r⁻¹² do in LJ?"), back: L("طرد تجريبي قصير المدى، مربع r⁻⁶ رخيص حسابياً.", "Short-range empirical repulsion; square of r⁻⁶, computationally cheap."), tags: ["mechanics"] },
  { id: "fc6", deck: "pme", front: L("لماذا PME؟", "Why PME?"), back: L("1/r بطيء الاضمحلال؛ PME يفصل قصيراً مباشراً وطويلاً في فورييه.", "1/r decays slowly; PME splits short-range direct and long-range Fourier."), tags: ["md"] },
  { id: "fc7", deck: "ensemble", front: L("NVT يحفظ ماذا؟", "What does NVT hold fixed?"), back: L("عدد الجسيمات، الحجم، ودرجة الحرارة (عبر منظم).", "Particle number, volume, and temperature (via a thermostat)."), tags: ["md"] },
  { id: "fc8", deck: "dt", front: L("لماذا 2 fs شائع؟", "Why is 2 fs common?"), back: L("مع قيود X–H تُزال أسرع حركة. 5 fs بلا قيود يكسر التكامل غالباً.", "With X–H constraints the fastest motion is removed. 5 fs unconstrained often breaks the integrator."), tags: ["md"] },
  { id: "fc9", deck: "kd", front: L("ΔG وKd", "ΔG and Kd"), back: L("ΔG° = RT ln(Kd / c°) عند معيار 1 M عادة.", "ΔG° = RT ln(Kd / c°) with a 1 M standard state typically."), tags: ["thermo"] },
  { id: "fc10", deck: "ic50", front: L("IC50 = Kd؟", "IC50 = Kd?"), back: L("لا. IC50 يعتمد على المقايسة والركيزة. Ki أقرب بعد نموذج تثبيط.", "No. IC50 depends on the assay and substrate. Ki is closer after an inhibition model."), tags: ["docking"] },
  { id: "fc11", deck: "tanimoto", front: L("تانيموتو 0.7", "Tanimoto 0.7"), back: L("عتبة شائعة تحت بروتوكول بصمة واحد، ليست ثابتة فيزيائية.", "A common cutoff under one fingerprint protocol, not a physical constant."), tags: ["chemo"] },
  { id: "fc12", deck: "lipinski", front: L("Lipinski قانون؟", "Is Lipinski a law?"), back: L("إرشاد تاريخي لصيغ فموية. يُكسر عمداً (ببتيدات، طبيعيات).", "A historical oral-drug heuristic. Broken on purpose (peptides, natural products)."), tags: ["admet"] },
  { id: "fc13", deck: "pains", front: L("PAINS يعني مرفوض؟", "Does PAINS mean reject?"), back: L("إنذار مقايسة لا حكم إعدام. تحقق تجريبياً.", "An assay alert, not a death sentence. Check experimentally."), tags: ["admet"] },
  { id: "fc14", deck: "mmpbsa", front: L("متى MM/PBSA غير ملائم؟", "When is MM/PBSA inappropriate?"), back: L("كيموتypes متباعدة، بلا نُسخ، فروق أصغر من الخطأ، أو ادّعاء ΔG تجريبي.", "Distant chemotypes, no replicas, gaps smaller than error, or a claim of experimental ΔG."), tags: ["fe"] },
  { id: "fc15", deck: "fep", front: L("FEP أفضل لـ", "FEP is best for"), back: L("ΔΔG نسبي داخل سلسلة متشابهة بنوافذ λ متداخلة.", "Relative ΔΔG inside a similar series with overlapping λ windows."), tags: ["fe"] },
  { id: "fc16", deck: "proton", front: L("خطأ بروتنة يفعل ماذا؟", "What does a protonation error do?"), back: L("يغيّر Coulomb في الجيب وقد يقلب ترتيب الالتحام.", "It rewrites pocket Coulomb and can invert docking ranks."), tags: ["prep"] },
  { id: "fc17", deck: "tip3p", front: L("لماذا TIP3P شائع؟", "Why is TIP3P common?"), back: L("رخيص ومتوافق مع حقول أُعدّت معه. ليس أدق ماء.", "Cheap and consistent with FFs built with it. Not the most accurate water."), tags: ["md"] },
  { id: "fc18", deck: "roc", front: L("AUC في الفرز", "AUC in screening"), back: L("قدرة البروتوكول على تمييز نشط/مخادع على تلك المجموعة فقط.", "The protocol’s ability to separate actives/decoys on that set only."), tags: ["docking"] },
  { id: "fc19", deck: "ad", front: L("نطاق التطبيق", "Applicability domain"), back: L("خارج النطاق التنبؤ تخمين. أعلنه.", "Outside the domain, a prediction is a guess. Declare it."), tags: ["qsar"] },
  { id: "fc20", deck: "replica", front: L("نُسخ مستقلة", "Independent replicas"), back: L("بذور/سرعات مختلفة. نفس البذرة ليست نسخة.", "Different seeds/velocities. The same seed is not a replica."), tags: ["md"] },
  { id: "fc21", deck: "alphafold", front: L("طية AlphaFold = هيئة مرتبطة؟", "AlphaFold fold = bound pose?"), back: L("لا. فرضية بنيوية. الجيب قد يكون مغلقاً.", "No. A structural hypothesis. The pocket may be closed."), tags: ["ml"] },
  { id: "fc22", deck: "exhaust", front: L("exhaustiveness يضمن الحد العالمي؟", "Does exhaustiveness guarantee the global min?"), back: L("لا. يزيد جهد البحث. لا يضمن.", "No. It increases search effort. It does not guarantee."), tags: ["docking"] },
  { id: "fc23", deck: "berendsen", front: L("Berendsen للإنتاج؟", "Berendsen for production?"), back: L("لا يولّد مجموعة صحيحة بصرامة. للاتزان بحذر؛ للإنتاج فكّر v-rescale/NH.", "It does not rigorously sample the ensemble. Equilibration with care; production: consider v-rescale/NH."), tags: ["md"] },
  { id: "fc24", deck: "ethics", front: L("انتقاء إطار جميل", "Picking a pretty frame"), back: L("انتقاء بصري. اذكر معيار الاختيار أو العنقود.", "Visual cherry-picking. State the selection rule or cluster."), tags: ["ethics"] },
];

export const mistakes: Mistake[] = [
  {
    id: "m1",
    title: L("الدرجة = الألفة", "Score = affinity"),
    whyWrong: L("دوال التقييم مرتِّبات تقريبية.", "Scoring functions are approximate rankers."),
    consequences: L("أولوية إصابات كاذبة وادّعاء اكتشاف.", "False hit priority and a discovery claim."),
    better: L("تحقق + طرائق متعامدة + تجربة.", "Validation + orthogonal methods + assay."),
    tags: ["docking"],
  },
  {
    id: "m2",
    title: L("RMSD مسطح = مستقر", "Flat RMSD = stable"),
    whyWrong: L("المسطّح قد يعني بئراً محلية أو قيوداً أو معاينة لم تبدأ.", "Flatness may mean a local well, restraints, or sampling that has not started."),
    consequences: L("ورقة تدّعي استقرار المعقّد بلا دليل طاقة.", "A paper claims complex stability without energy evidence."),
    better: L("نُسخ، مشاهدات أخرى، ومعيار تقارب مكتوب مسبقاً.", "Replicas, other observables, and a pre-written convergence criterion."),
    tags: ["md"],
  },
  {
    id: "m3",
    title: L("تجاهل البروتنة", "Ignoring protonation"),
    whyWrong: L("الشحنة تغيّر Coulomb وكل هيئة.", "Charge rewrites Coulomb and every pose."),
    consequences: L("جسور ملحية وهمية أو مفقودة.", "Fake or missing salt bridges."),
    better: L("pKa، توتومر، وفحص His/Asp/Glu قبل الالتحام.", "pKa, tautomer, and His/Asp/Glu inspection before docking."),
    tags: ["prep"],
  },
  {
    id: "m4",
    title: L("حذف المعدن والماء", "Deleting metal and water"),
    whyWrong: L("قد يكونان جزءاً من الفارماكوفور.", "They may be part of the pharmacophore."),
    consequences: L("جيب هندسي كاذب.", "A fake geometric pocket."),
    better: L("حفظ ما هو محفوظ عائلياً أو معلَّل.", "Keep what is family-conserved or justified."),
    tags: ["prep"],
  },
  {
    id: "m5",
    title: L("MM/PBSA كمقياس", "MM/PBSA as an assay"),
    whyWrong: L("خطأ غالباً أكبر من الفروق بين كيموتypes متباعدة.", "Error is often larger than gaps between distant chemotypes."),
    consequences: L("ترتيب تخليق وهمي.", "A fictional synthesis ranking."),
    better: L("سلسلة ضيقة، نُسخ، أو FEP/تجربة.", "Narrow series, replicas, or FEP/assay."),
    tags: ["fe"],
  },
  {
    id: "m6",
    title: L("100 ns بلا نُسخ", "100 ns with no replicas"),
    whyWrong: L("حظ البذرة ليس إحصاءً.", "Seed luck is not a statistic."),
    consequences: L("بقاء أو خروج غير قابل للتعميم.", "Stay or leave that will not generalise."),
    better: L("ثلاث نُسخ على الأقل وسؤال صادق عن النافذة.", "At least three replicas and an honest window claim."),
    tags: ["md"],
  },
  {
    id: "m7",
    title: L("خلط IC50 وKd", "Mixing IC50 and Kd"),
    whyWrong: L("IC50 شرط مقايسة.", "IC50 is assay-conditioned."),
    consequences: L("مقارنة عبر أوراق بلا معنى.", "Cross-paper comparisons without meaning."),
    better: L("سمِّ النهاية والشروط.", "Name the endpoint and conditions."),
    tags: ["thermo"],
  },
  {
    id: "m8",
    title: L("QSAR خارج النطاق", "QSAR outside the domain"),
    whyWrong: L("النموذج يتعلم جيرانه لا الكون.", "The model learned its neighbours, not the universe."),
    consequences: L("نانومولار متخيَّل.", "Imaginary nanomolar."),
    better: L("أعلن AD ولا تنشر خارجها كحقيقة.", "Declare AD and do not publish outside it as fact."),
    tags: ["qsar"],
  },
  {
    id: "m9",
    title: L("لغة «دواء واعد» من تحام", "“Promising drug” from docking"),
    whyWrong: L("الدواء قرار سريري/ADMET/تجربة.", "A drug is a clinical/ADMET/assay decision."),
    consequences: L("رفض المحكّم ومحق.", "A referee reject, deserved."),
    better: L("«فرضية هيئة لاختبار تجريبي».", "“A pose hypothesis for experimental testing”."),
    tags: ["criticism"],
  },
  {
    id: "m10",
    title: L("خلط حقول القوة", "Mixing force fields"),
    whyWrong: L("فلسفات شحن وvdW مختلفة.", "Different charge and vdW philosophies."),
    consequences: L("طاقة غير فيزيائية.", "Unphysical energy."),
    better: L("اتساق بروتين–ليغند–ماء.", "Protein–ligand–water consistency."),
    tags: ["mechanics"],
  },
];

export const commands: CommandEntry[] = [
  {
    id: "c-pdb2gmx",
    software: "GROMACS",
    command: "gmx pdb2gmx -f protein.pdb -o processed.gro -water tip3p",
    purpose: L("بناء طوبولوجيا البروتين واختيار الحقل والماء.", "Build protein topology; choose FF and water."),
    input: L("PDB منظّف نسبياً.", "A reasonably cleaned PDB."),
    output: L(".gro و topol.top و posre.", ".gro, topol.top, and posre."),
    meaning: L("هنا تُثبَّت فيزياء الذرات: أنواع، شحنات، روابط.", "This freezes the atoms’ physics: types, charges, bonds."),
    errors: L("بقايا غير قياسية، هيئات بديلة، أو سلسلة ناقصة.", "Nonstandard residues, altlocs, or a missing chain."),
    why: L("بلا طوبولوجيا لا توجد قوى.", "Without a topology there are no forces."),
  },
  {
    id: "c-editconf",
    software: "GROMACS",
    command: "gmx editconf -f processed.gro -o boxed.gro -c -d 1.0 -bt dodecahedron",
    purpose: L("صندوق ودورانcentering مع هامش للمذيب.", "Box and centering with a solvent margin."),
    input: L("بنية بعد pdb2gmx.", "Structure after pdb2gmx."),
    output: L("بنية في صندوق.", "A boxed structure."),
    meaning: L("الهامش قرار PBC: صغير جداً تلامس الصور.", "The margin is a PBC decision: too small and images touch."),
    errors: L("PBC لاحق إن كان -d أصغر من القطع.", "Later PBC artifacts if -d is smaller than the cutoff."),
    why: L("الصندوق جزء من الفيزياء الدورية.", "The box is part of the periodic physics."),
  },
  {
    id: "c-solvate",
    software: "GROMACS",
    command: "gmx solvate -cp boxed.gro -cs spc216.gro -o solv.gro -p topol.top",
    purpose: L("ملء الصندوق بماء النموذج المختار.", "Fill the box with the chosen water model."),
    input: L("صندوق فارغ وطوبولوجيا.", "Empty box and topology."),
    output: L("نظام مُذاب وtop محدّث.", "A solvated system and updated top."),
    meaning: L("الماء شريك ارتباط لا خلفية.", "Water is a binding partner, not wallpaper."),
    errors: L("عدم تحديث top يُسقط grompp.", "Forgetting to update top fails grompp."),
    why: L("الإذابة الصريحة تُكلّف وتعطي فيزياء أفضل للقطبية.", "Explicit solvation costs, and gives better polar physics."),
  },
  {
    id: "c-grompp",
    software: "GROMACS",
    command: "gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr",
    purpose: L("تجميع مدخلات إلى tpr: فحص المsdp والتوافق.", "Assemble inputs into a tpr: check mdp and consistency."),
    input: L("mdp + إحداثيات + top.", "mdp + coordinates + top."),
    output: L("tpr أو أخطاء صريحة.", "A tpr, or explicit errors."),
    meaning: L("grompp محامٍ: يرفض تناقضات قبل المضي.", "grompp is a lawyer: it refuses contradictions before running."),
    errors: L("شحنة غير متعادلة، قطع > نصف الصندوق، مفاتيح مهجورة.", "Nonzero charge, cutoff > half box, deprecated keys."),
    why: L("الفشل هنا أرخص من مسار فاسد.", "Failure here is cheaper than a corrupt trajectory."),
  },
  {
    id: "c-genion",
    software: "GROMACS",
    command: "gmx genion -s ions.tpr -o ions.gro -p topol.top -neutral",
    purpose: L("تعادل الشحنة بأيونات.", "Neutralise charge with ions."),
    input: L("tpr مُذاب.", "A solvated tpr."),
    output: L("أيونات بدل جزيئات ماء.", "Ions replacing some waters."),
    meaning: L("الشحنة الصافية تشوّه PME الدوري.", "Net charge distorts periodic PME."),
    errors: L("مجموعة solvent خاطئة.", "Wrong solvent group."),
    why: L("الحياد شرط كهرومستاتيك دوري نظيف.", "Neutrality is a clean periodic-electrostatics condition."),
  },
  {
    id: "c-mdrun",
    software: "GROMACS",
    command: "gmx mdrun -deffnm md -cpi md.cpt",
    purpose: L("تكامل الحركة؛ -cpi لاستئناف.", "Integrate motion; -cpi to restart."),
    input: L("tpr (و cpt إن وُجد).", "A tpr (and cpt if present)."),
    output: L("xtc/trr, edr, log, cpt.", "xtc/trr, edr, log, cpt."),
    meaning: L("هنا تُخلَق المعاينة. الجودة من المsdp لا من طول الأمر.", "Sampling is created here. Quality is the mdp, not the command length."),
    errors: L("LINCS warnings، انفجار طاقة، امتلاء قرص.", "LINCS warnings, energy explosion, full disk."),
    why: L("checkpoint يحمي الإحصاء من قتل العنقود.", "A checkpoint protects statistics from a cluster kill."),
  },
  {
    id: "c-rms",
    software: "GROMACS",
    command: "gmx rms -s md.tpr -f md.xtc -o rmsd.xvg",
    purpose: L("RMSD بعد اختيار مجموعات المواءمة والقياس.", "RMSD after choosing fit and measurement groups."),
    input: L("tpr ومسار.", "tpr and trajectory."),
    output: L("منحنى زمني.", "A time series."),
    meaning: L("انحراف عن مرجع بعد إزالة الانزلاق الصلب إن حاذيت.", "Deviation from a reference after removing rigid drift if you fitted."),
    errors: L("محاذاة على الليغند ثم قياس الليغند يخفي الحركة النسبية.", "Fitting on the ligand then measuring the ligand hides relative motion."),
    why: L("المواءمة قرار علمي يُذكر.", "The fit is a scientific decision that must be stated."),
  },
  {
    id: "c-vina",
    software: "AutoDock Vina",
    command: "vina --receptor rec.pdbqt --ligand lig.pdbqt --config conf.txt --out out.pdbqt",
    purpose: L("بحث هيئات وتقييم تقريبي.", "Search poses and score approximately."),
    input: L("مستقبل وليغند pdbqt وصندوق.", "Receptor and ligand pdbqt plus a box."),
    output: L("هيئات مرتّبة بدرجات.", "Ranked poses with scores."),
    meaning: L("exhaustiveness جهد بحث لا ضمان حد عالمي.", "exhaustiveness is search effort, not a global-min guarantee."),
    errors: L("صندوق بعيد عن الجيب، بروتنة خاطئة، ليغند غير مُحضَّر.", "Box off the pocket, wrong protonation, unprepared ligand."),
    why: L("الدرجة ليست Kd.", "The score is not Kd."),
  },
];

export const equations: EquationEntry[] = [
  {
    id: "eq-dg",
    latex: "\\Delta G = \\Delta H - T\\Delta S",
    name: L("تجزئة غيبس", "Gibbs split"),
    meaning: L("ارتباط مواتٍ من إنثالبي أو إنتروبي أو كليهما.", "Favourable binding from enthalpy, entropy, or both."),
    variables: [
      { symbol: "\\Delta H", name: L("الإنثالبي", "Enthalpy"), unit: L("kcal mol⁻¹", "kcal mol⁻¹") },
      { symbol: "T\\Delta S", name: L("حد الإنتروبي", "Entropy term"), unit: L("kcal mol⁻¹", "kcal mol⁻¹") },
    ],
    interpretation: L("تعويض إنثالبي−إنتروبي شائع. لا تفسّر القوة من عدد H-bonds وحده.", "Enthalpy–entropy compensation is common. Do not explain potency from H-bond count alone."),
    application: L("ITC مقابل حساب نهاية الحالة.", "ITC versus an end-state calculation."),
    related: ["eq-k", "l10-dg"],
  },
  {
    id: "eq-k",
    latex: "\\Delta G^{\\circ} = RT \\ln (K_d / c^{\\circ})",
    name: L("ارتباط وKd", "Binding and Kd"),
    meaning: L("المعيار c° (غالباً 1 M) جزء من التعريف.", "The standard state c° (often 1 M) is part of the definition."),
    variables: [{ symbol: "K_d", name: L("ثابت التفكك", "Dissociation constant"), unit: L("M", "M") }],
    interpretation: L("رتبة عشرية في Kd ≈ 1.4 kcal/mol عند 298 K.", "A tenfold Kd shift is ≈ 1.4 kcal/mol at 298 K."),
    application: L("تحويل مقايسة إلى طاقة، لا العكس من درجة تحام.", "Convert an assay to energy — not a docking score the other way."),
    related: ["eq-dg", "l8-affinity"],
  },
  {
    id: "eq-f",
    latex: "\\mathbf{F} = -\\nabla V",
    name: L("القوة من الكمون", "Force from the potential"),
    meaning: L("الذرة تتدحرج على سطح V الذي عرّفه الحقل.", "The atom rolls on the V surface defined by the FF."),
    variables: [{ symbol: "V", name: L("كمون المجال", "Force-field potential") }],
    interpretation: L("خطأ V خطأ حركة.", "A wrong V is wrong motion."),
    application: L("كل خطوة MD.", "Every MD step."),
    related: ["eq-newton", "l9-newton"],
  },
  {
    id: "eq-newton",
    latex: "\\mathbf{F}_i = m_i \\mathbf{a}_i",
    name: L("نيوتن", "Newton"),
    meaning: L("تسارع يتناسب عكسياً مع الكتلة.", "Acceleration inverse to mass."),
    variables: [{ symbol: "m_i", name: L("كتلة الذرة", "Atomic mass") }],
    interpretation: L("الهيدروجين يحدّ الخطوة ما لم يُقيَّد.", "Hydrogen limits the step unless constrained."),
    application: L("قيود LINCS/SHAKE.", "LINCS/SHAKE constraints."),
    related: ["eq-f"],
  },
  {
    id: "eq-lj",
    latex: "E_{\\mathrm{LJ}}=4\\varepsilon\\left[(\\sigma/r)^{12}-(\\sigma/r)^{6}\\right]",
    name: L("لينارد-جونز", "Lennard-Jones"),
    meaning: L("طرد قصير وتشتت.", "Short repulsion and dispersion."),
    variables: [
      { symbol: "\\varepsilon", name: L("عمق البئر", "Well depth") },
      { symbol: "\\sigma", name: L("مسافة صفر الطاقة", "Zero-energy distance") },
    ],
    interpretation: L("الأس 12 ملائم لا مقدّس.", "The 12 is convenient, not sacred."),
    application: L("تصادم ليغند–جيب.", "Ligand–pocket clash."),
    related: ["l6-lj"],
  },
  {
    id: "eq-coulomb",
    latex: "E_{\\mathrm{el}}=\\frac{1}{4\\pi\\varepsilon_0}\\frac{q_i q_j}{r_{ij}}",
    name: L("كولوم", "Coulomb"),
    meaning: L("نقاط شحن.", "Point charges."),
    variables: [{ symbol: "q", name: L("شحنة جزئية", "Partial charge") }],
    interpretation: L("طريقة اشتقاق q قرار فيزيائي.", "How q is derived is a physics decision."),
    application: L("برتنة ومعادن وPME.", "Protonation, metals, PME."),
    related: ["l6-coulomb"],
  },
  {
    id: "eq-rmsd",
    latex: "\\mathrm{RMSD}=\\sqrt{\\frac{1}{N}\\sum_i \\| \\mathbf{x}_i - \\mathbf{y}_i \\|^2}",
    name: L("RMSD", "RMSD"),
    meaning: L("مسافة إقليدية متوسطة بعد مواءمة عادة.", "Mean Euclidean distance, usually after a fit."),
    variables: [{ symbol: "N", name: L("عدد الذرات", "Number of atoms") }],
    interpretation: L("ليس طاقة ولا تقارب.", "Neither energy nor convergence."),
    application: L("إعادة تحام ومسارات.", "Redocking and trajectories."),
    related: ["l9-rmsd"],
  },
  {
    id: "eq-tanimoto",
    latex: "T(A,B)=\\frac{|A \\cap B|}{|A \\cup B|}",
    name: L("تانيموتو", "Tanimoto"),
    meaning: L("تقاطع على اتحاد بتات.", "Intersection over union of bits."),
    variables: [{ symbol: "A,B", name: L("مجموعتا البتات", "Bit sets") }],
    interpretation: L("يعتمد على البصمة. 0.7 ليست ثابتة.", "Depends on the fingerprint. 0.7 is not a constant."),
    application: L("بحث تشابه وتجميع.", "Similarity search and clustering."),
    related: ["l5-fp"],
  },
];

export const dictionary: DictEntry[] = [
  {
    id: "d-ff",
    term: "Force field",
    termAr: "مجال قسري / حقل قوة",
    definition: L("نموذج تجريبي لطاقة الوضع الذرية: bonded + nonbonded.", "An empirical atomic potential: bonded + nonbonded."),
    equation: "V(r) = V_bonded + V_nonbonded",
    use: L("MD وتقليل الطاقة وبعض دوال التقييم.", "MD, minimization, and some scoring functions."),
    limitations: L("لا تكسر روابط عادة، شحنات ثابتة غالباً، نقل من جزيئات صغيرة.", "Usually no bond breaking, often fixed charges, transfer from small molecules."),
    related: ["d-gaff", "l6-etotal"],
    software: ["GROMACS", "AMBER", "OpenMM"],
  },
  {
    id: "d-score",
    term: "Scoring function",
    termAr: "دالة تقييم",
    definition: L("دالة رخيصة لترتيب هيئات أو مركبات.", "A cheap function for ranking poses or compounds."),
    use: L("التحام وفرز.", "Docking and screening."),
    limitations: L("ليست ΔG. منحازة لقواعد بيانات التدريب.", "Not ΔG. Biased by training databases."),
    related: ["d-dg", "l8-scoring"],
    software: ["AutoDock Vina", "Gnina"],
  },
  {
    id: "d-dg",
    term: "Binding free energy",
    termAr: "طاقة ارتباط حرة",
    definition: L("فرق غيبس بين معقد وحالة منفصلة عند معيار.", "Gibbs difference between complex and separated states at a standard state."),
    equation: "\\Delta G^{\\circ} = RT \\ln (K_d/c^{\\circ})",
    use: L("تفسير الألفة والمقارنة داخل سلسلة.", "Interpreting affinity and comparing inside a series."),
    limitations: L("صعب حسابياً. MM/PBSA تقريب نهاية حالة.", "Hard to compute. MM/PBSA is an end-state approximation."),
    related: ["d-score", "l10-dg"],
  },
  {
    id: "d-gaff",
    term: "GAFF / GAFF2",
    termAr: "حقل ليغند عام",
    definition: L("حقل عام لجزيئات عضوية صغيرة متوافق مع Amber.", "A general small-molecule FF compatible with Amber."),
    use: L("طوبولوجيا الليغند قبل MD.", "Ligand topology before MD."),
    limitations: L("شحنات وtorsion قد تضعف على كيمياء غير مألوفة.", "Charges and torsions may weaken on unfamiliar chemistry."),
    related: ["d-ff"],
    software: ["AmberTools"],
  },
  {
    id: "d-pme",
    term: "PME",
    termAr: "Particle Mesh Ewald",
    definition: L("تقسيم كولوم إلى مباشر قصير وفورييه طويل.", "Split Coulomb into short-range direct and long-range Fourier."),
    use: L("MD صريح المذيب الدوري.", "Periodic explicit-solvent MD."),
    limitations: L("يفترض دورية. الشحنة الصافية مشكلة.", "Assumes periodicity. Net charge is a problem."),
    related: ["l9-pbc"],
  },
  {
    id: "d-ad",
    term: "Applicability domain",
    termAr: "نطاق التطبيق",
    definition: L("منطقة كيميائية يُوثَق فيها النموذج.", "The chemical region where the model is trusted."),
    use: L("QSAR وML وADMET.", "QSAR, ML, and ADMET."),
    limitations: L("تعريفه نفسه نموذج.", "Its definition is itself a model."),
    related: ["l12-ad"],
  },
];

export const vivaQuestions: VivaQuestion[] = [
  {
    id: "v1",
    difficulty: "beginner",
    question: L("لماذا لا تساوي درجة الالتحام IC50؟", "Why does a docking score not equal IC50?"),
    ideal: L("الدرجة ترتيب هيئة تقريبي. IC50 مقايسة تعتمد على الركيزة والبروتين. لا اشتقاق ثرموديناميكي بينهما.", "The score ranks poses approximately. IC50 is an assay depending on substrate and protein. No thermodynamic derivation links them."),
    followUp: L("ماذا تفعل إن وافقت الدرجة مقايسة لمركب واحد؟", "What if the score matches an assay for one compound?"),
    pitfalls: L("«لأن الوحدات kcal/mol». الشبه اللغوي ليس اشتقاقاً.", "“Because the units are kcal/mol.” Linguistic resemblance is not a derivation."),
  },
  {
    id: "v2",
    difficulty: "intermediate",
    question: L("ما المعنى الفيزيائي لـ RMSD؟", "What is the physical meaning of RMSD?"),
    ideal: L("مسافة هندسية عن مرجع بعد مواءمة. ليست طاقة ولا دليلاً على حوض ارتباط.", "A geometric distance from a reference after a fit. Not energy, not proof of a binding basin."),
    followUp: L("كيف تختار مجموعة المواءمة؟", "How do you choose the fit group?"),
    pitfalls: L("«إذا كان أقل من 2 Å فالمعقد مستقر».", "“If it is below 2 Å the complex is stable.”"),
  },
  {
    id: "v3",
    difficulty: "advanced",
    question: L("كيف تعرف أن المحاكاة تقاربت؟", "How do you know the simulation converged?"),
    ideal: L("لا تعرف بالمعنى المطلق. تُظهر استقرار مشاهدات متعددة عبر نُسخ وكتل، وتعلن أن الأحداث الأبطأ قد تكون غائبة.", "You never know absolutely. You show multiple observables stable across replicas and blocks, and admit slower events may be absent."),
    followUp: L("ماذا لو اختلفت ثلاث نُسخ؟", "What if three replicas disagree?"),
    pitfalls: L("مسار واحد مسطح.", "One flat trajectory."),
  },
  {
    id: "v4",
    difficulty: "advanced",
    question: L("ما افتراضات MM/PBSA؟", "What are MM/PBSA’s assumptions?"),
    ideal: L("نهاية حالة، مذيب مستمر، غالباً إنتروبي ضعيف، وهيئات من حقل تقريبي. الخطأ قد يبتلع ΔΔG الصغير.", "End-state, continuum solvent, often weak entropy, poses from an approximate FF. Error can swallow small ΔΔG."),
    followUp: L("متى ترفض استخدامها؟", "When would you refuse to use it?"),
    pitfalls: L("جدول بثلاث خانات كحقيقة.", "A three-decimal table as truth."),
  },
  {
    id: "v5",
    difficulty: "researcher",
    question: L("لماذا هذا الحقل لا غيره؟", "Why this force field rather than another?"),
    ideal: L("توافق ليغند–بروتين–ماء، أدبيات العائلة، وما لن تقيسه. اذكر الثمن مقابل CHARMM/OPLS.", "Ligand–protein–water consistency, family literature, and what you will not measure. State the price versus CHARMM/OPLS."),
    followUp: L("ماذا يتغيّر إن غيّرت الماء فقط؟", "What changes if you change only the water?"),
    pitfalls: L("«لأن المختبر يستخدمه» بلا ثمن.", "“Because the lab uses it” with no price."),
  },
  {
    id: "v6",
    difficulty: "professor",
    question: L("ما الذي يُفنّد فرضيتك دون تجربة رطبة؟", "What would falsify your hypothesis without a wet assay?"),
    ideal: L("معيار مكتوب مسبقاً: فشل إعادة التحام، خروج في أغلب النُسخ، عدم تداخل λ، أو AUC دون عتبة.", "A pre-written criterion: redock failure, unbinding in most replicas, no λ overlap, or AUC below a threshold."),
    followUp: L("هل النتيجة السلبية فشل الدراسة؟", "Is a negative result a failed study?"),
    pitfalls: L("تحريك العتبة بعد الرقم.", "Moving the threshold after the number."),
  },
  {
    id: "v7",
    difficulty: "intermediate",
    question: L("ماذا يفعل exhaustiveness؟", "What does exhaustiveness do?"),
    ideal: L("يزيد جهد البحث العشوائي. لا يضمن الحد الأدنى العالمي ولا صحة الموقع.", "Increases stochastic search effort. Guarantees neither the global minimum nor the correct site."),
    followUp: L("لماذا قد تتغيّر الهيئة عند تكرار التشغيل؟", "Why might the pose change on a rerun?"),
    pitfalls: L("«8 يعني بحثاً كاملاً».", "“8 means a complete search.”"),
  },
  {
    id: "v8",
    difficulty: "researcher",
    question: L("اشرح PME بجملة للفيزيائي وجملة للكيميائي.", "Explain PME in one sentence for a physicist and one for a chemist."),
    ideal: L("فيزيائي: Ewald على شبكة لتسريع 1/r الدوري. كيميائي: لا نقطع الكهروستاتيك بجدار فجّ في صندوق دوري.", "Physicist: Ewald on a mesh to speed periodic 1/r. Chemist: we do not cut electrostatics with a naive wall in a periodic box."),
    followUp: L("ماذا لو كانت الشحنة الصافية غير صفر؟", "What if net charge is nonzero?"),
    pitfalls: L("«PME سحر GPU».", "“PME is a GPU spell.”"),
  },
];

export const comparisons: Comparison[] = [
  {
    id: "cmp-dock-md",
    a: L("التحام", "Docking"),
    b: L("ديناميكا جزيئية", "Molecular dynamics"),
    rows: [
      { dim: L("السؤال", "Question"), a: L("هيئة ممكنة رخيصة", "A cheap possible pose"), b: L("حركة ومعاينة تحت نموذج", "Motion and sampling under a model") },
      { dim: L("التكلفة", "Cost"), a: L("ثوانٍ–دقائق", "Seconds–minutes"), b: L("ساعات–أسابيع", "Hours–weeks") },
      { dim: L("ليست", "Is not"), a: L("ΔG", "ΔG"), b: L("فيلم الجزيء الحقيقي", "A movie of the real molecule") },
    ],
  },
  {
    id: "cmp-pb-fep",
    a: L("MM/PBSA", "MM/PBSA"),
    b: L("FEP نسبي", "Relative FEP"),
    rows: [
      { dim: L("المسار", "Path"), a: L("نهاية حالة تقريبية", "Approximate end-state"), b: L("تحول كيميائي بنافذة λ", "Alchemical path with λ windows") },
      { dim: L("الاستخدام", "Use"), a: L("إشارة داخل سلسلة ضيقة", "A hint inside a narrow series"), b: L("فرق ذرة يستحق عنقوداً", "An atom difference worth a cluster") },
    ],
  },
  {
    id: "cmp-vina-glide",
    a: L("Vina (مفهوم)", "Vina (concept)"),
    b: L("Glide (مفهوم)", "Glide (concept)"),
    rows: [
      { dim: L("الوصول", "Access"), a: L("مفتوح شائع تعليمياً", "Open, common in teaching"), b: L("تجاري؛ لا ندّعي تشغيلاً هنا", "Commercial; we do not claim to run it here") },
      { dim: L("المشترك", "Shared"), a: L("بحث + تقييم ≠ محاكاة ارتباط", "Search + score ≠ binding simulation"), b: L("نفس الحد: تحقق الموقع والبروتنة", "Same limit: validate site and protonation") },
    ],
  },
  {
    id: "cmp-tip3-tip4",
    a: L("TIP3P", "TIP3P"),
    b: L("TIP4P-class", "TIP4P-class"),
    rows: [
      { dim: L("التكلفة", "Cost"), a: L("أرخص", "Cheaper"), b: L("موقع رابع؛ أثقل", "Fourth site; heavier") },
      { dim: L("الدقة", "Accuracy"), a: L("شائع مع Amber", "Common with Amber"), b: L("بعض خصائص الماء أفضل أحياناً", "Some water properties sometimes better") },
      { dim: L("الاختيار", "Choice"), a: L("اتساق مع الحقل", "Consistency with the FF"), b: L("اتساق مع الحقل أيضاً", "Also consistency with the FF") },
    ],
  },
  {
    id: "cmp-explicit-implicit",
    a: L("مذيب صريح", "Explicit solvent"),
    b: L("مذيب ضمني", "Implicit solvent"),
    rows: [
      { dim: L("الفيزياء", "Physics"), a: L("جزيئات ماء وجسور", "Water molecules and bridges"), b: L("متصل عازل", "A dielectric continuum") },
      { dim: L("التكلفة", "Cost"), a: L("عالية", "High"), b: L("أقل", "Lower") },
      { dim: L("الخطر", "Risk"), a: L("معاينة ناقصة", "Thin sampling"), b: L("فقدان ماء محبوس", "Losing trapped water") },
    ],
  },
];

export const caseStudies: CaseStudy[] = [
  {
    id: "cs-kinase",
    title: L("كيناز — مثال تعليمي Abl/imatinib", "Kinase — educational Abl/imatinib"),
    targetClass: L("كيناز تيروسين", "Tyrosine kinase"),
    biology: L("مسارات انقسام. مثبطات ATP-site معروفة سريرياً. هذا ملف تعليمي لا ادعاء اكتشاف.", "Division pathways. ATP-site inhibitors are clinically known. Educational, not a discovery claim."),
    structure: L("1IEP بنية عامة لـ Abl مع imatinib (STI). افحص الجودة قبل التصميم.", "1IEP is a public Abl–imatinib (STI) structure. Inspect quality before design."),
    pocket: L("مفصلة hinge وجيب خلفي كاره للماء. DFG-in/out يغيّر الشكل.", "Hinge and a hydrophobic back pocket. DFG-in/out changes the shape."),
    design: L("حافظ على H-bond المفصلة؛ عدّل الذيل للانتقائية بحذر.", "Keep the hinge H-bond; modify the tail for selectivity carefully."),
    docking: L("إعادة تحام STI قبل أي مكتبة. فشل إعادة التحام يوقف الفرز.", "Redock STI before any library. Redock failure stops screening."),
    md: L("نُسخ إن سألت عن بقاء الذيل لا عن «دواء».", "Replicas if you ask about tail persistence, not about a “drug”."),
    energy: L("لا MM/PBSA بين كيموتypes بعيدة عن STI.", "No MM/PBSA across chemotypes far from STI."),
    optimization: L("الانتقائية مقابل كينازات القريب مشكلة جيوب متشابهة.", "Selectivity versus nearby kinases is a similar-pocket problem."),
    caveat: L("بيانات تعليمية. imatinib دواء معروف تجريبياً؛ الحساب هنا تفسير لا اكتشاف.", "Educational. Imatinib is experimentally a known drug; computation here interprets, it does not discover."),
    pdb: "1IEP",
  },
  {
    id: "cs-gpcr",
    title: L("GPCR — حذر بنيوي", "GPCR — structural caution"),
    targetClass: L("مستقبل مقترن بالبروتين G", "GPCR"),
    biology: L("إشارات غشائية. حالات نشطة/خاملة.", "Membrane signalling. Active/inactive states."),
    structure: L("بلورات/cryo-EM مع غشاء ودهون. AlphaFold قد يُغلق الجيب.", "Crystals/cryo-EM with membrane and lipids. AlphaFold may close the pocket."),
    pocket: L("جيب orthosteric عميق؛ مواقع allosteric شائعة.", "A deep orthosteric pocket; allosteric sites are common."),
    design: L("لا تخلط حالة activation.", "Do not mix activation states."),
    docking: L("الصندوق في الغشاء سهّل الخطأ. وثّق.", "A membrane box is easy to get wrong. Document it."),
    md: L("غشاء صريح مكلف. أعلن النموذج الدهني.", "Explicit membrane is costly. Name the lipid model."),
    energy: L("ماء محبوس في الجيب قد يهيمن.", "Trapped pocket water may dominate."),
    optimization: L("BBB وlogD إن كان الهدف مركزياً.", "BBB and logD if the target is central."),
    caveat: L("مثال صنف لا بروتوكول جاهز لهدف غير محدد.", "A class example, not a ready protocol for an unnamed target."),
  },
  {
    id: "cs-protease",
    title: L("بروتياز — حرباء وماء", "Protease — warhead and water"),
    targetClass: L("بروتياز", "Protease"),
    biology: L("قطع ببتيد. مثبطات تساهمية وغير تساهمية.", "Peptide cleavage. Covalent and noncovalent inhibitors."),
    structure: L("حفرة حفزية مع ثالوث أو ثنائي. افحص حالة Cys/Ser.", "A catalytic cleft with a triad or dyad. Inspect Cys/Ser state."),
    pocket: L("Subsites S1–S3 تُعرِّف الانتقائية.", "Subsites S1–S3 define selectivity."),
    design: L("حرباء ليست درجة Vina.", "A warhead is not a Vina score."),
    docking: L("التحام تساهمي يفرض الرابطة لا الحركية.", "Covalent docking imposes the bond, not the kinetics."),
    md: L("MM لا يكوّن الرابطة. QM/MM أو مقايسة k_inact.", "MM does not form the bond. QM/MM or a k_inact assay."),
    energy: L("ماء في S1 قد يكون الفارماكوفور.", "Water in S1 may be the pharmacophore."),
    optimization: L("ببتيدوميتيك مقابل نفاذية.", "Peptidomimetic versus permeability."),
    caveat: L("تعليمي. لا تختلق IC50.", "Educational. Do not invent IC50."),
  },
];

export const labs: SoftwareLab[] = [
  {
    id: "lab-vina",
    title: L("مختبر Vina", "Vina laboratory"),
    software: "AutoDock Vina",
    summary: L("من pdbqt إلى قراءة الهيئة، مع أن الدرجة ليست ΔG.", "From pdbqt to reading the pose — the score is not ΔG."),
    steps: [
      {
        id: "s1",
        title: L("حضّر المستقبل", "Prepare the receptor"),
        body: L("أزل الليغند إن لزم، عيّن بروتنة، اكتب pdbqt.", "Remove ligand if needed, assign protonation, write pdbqt."),
        why: L("الشحنة والهيدروجين جزء من الفيزياء.", "Charge and hydrogens are part of the physics."),
        whatIf: L("His خاطئ يقلب الرتبة.", "A wrong His can invert ranks."),
        errors: L("بقايا ناقصة تُفتح كجيب كاذب.", "Missing residues open a fake pocket."),
      },
      {
        id: "s2",
        title: L("عرّف الصندوق", "Define the box"),
        command: "vina --receptor rec.pdbqt --ligand lig.pdbqt --center_x C --size_x S --exhaustiveness 8",
        body: L("الصندوق على دليل الجيب (ليغند بلوري أو موقع معلَّل).", "Box on pocket evidence (crystal ligand or a justified site)."),
        why: L("الخوارزمية تملأ ما تعطيها.", "The algorithm fills what you give it."),
        whatIf: L("صندوق كبير جداً يبحث السطح.", "A huge box searches the surface."),
      },
      {
        id: "s3",
        title: L("اقرأ الهيئة لا الرقم", "Read the pose, not the number"),
        body: L("هل المفصلة صحيحة؟ هل هناك clash؟", "Is the hinge right? Is there a clash?"),
        why: L("العين تمسك ما تفوته الدرجة.", "The eye catches what the score misses."),
      },
    ],
  },
  {
    id: "lab-gromacs",
    title: L("مختبر GROMACS", "GROMACS laboratory"),
    software: "GROMACS",
    summary: L("من pdb2gmx إلى rms، أمراً فأمراً.", "From pdb2gmx to rms, command by command."),
    steps: [
      {
        id: "g1",
        title: L("طوبولوجيا", "Topology"),
        command: "gmx pdb2gmx -f protein.pdb -o processed.gro -water tip3p",
        body: L("اختر حقلاً متوافقاً مع ليغندك.", "Choose a field compatible with your ligand."),
        why: L("هنا تُولد القوى.", "Forces are born here."),
        errors: L("residue غير قياسي.", "A nonstandard residue."),
      },
      {
        id: "g2",
        title: L("صندوق وماء وأيونات", "Box, water, ions"),
        body: L("هامش، نموذج ماء، تعادل شحنة.", "Margin, water model, charge neutralization."),
        why: L("PBE والكهروستاتيك الدوري.", "PBC and periodic electrostatics."),
        whatIf: L("صندوق قصير → تلامس الصور.", "Short box → image contacts."),
      },
      {
        id: "g3",
        title: L("تقليل واتزان وإنتاج", "Minimize, equilibrate, produce"),
        command: "gmx mdrun -deffnm nvt",
        body: L("NVT ثم NPT ثم إنتاج. thermostat/barostat قرارات.", "NVT then NPT then production. Thermostat/barostat are decisions."),
        why: L("الإنتاج على نظام غير متزن يقيس التحضير.", "Production on an unequilibrated system measures preparation."),
      },
      {
        id: "g4",
        title: L("تحليل صادق", "Honest analysis"),
        command: "gmx rms -s md.tpr -f md.xtc -o rmsd.xvg",
        body: L("محاذاة العمود الفقري قبل RMSD الليغند. نُسخ.", "Fit backbone before ligand RMSD. Replicas."),
        why: L("وإلا تقيس انزلاق الصندوق.", "Otherwise you measure box drift."),
      },
    ],
  },
  {
    id: "lab-rdkit",
    title: L("مختبر RDKit (مفهوم)", "RDKit laboratory (concept)"),
    software: "RDKit",
    summary: L("واصفات وتشابه — الشيفرة في مختبر بايثون بالأكاديمية.", "Descriptors and similarity — code lives in the academy Python lab."),
    steps: [
      {
        id: "r1",
        title: L("حلّل SMILES", "Parse SMILES"),
        body: L("MolFromSmiles قد يعيد None. هذه حالة علمية.", "MolFromSmiles may return None. That is a scientific case."),
        why: L("الصمت بالصفر يلوّث النموذج.", "Silent zeros pollute the model."),
      },
      {
        id: "r2",
        title: L("بصمة مورغان", "Morgan fingerprint"),
        body: L("ثبّت نصف القطر وnBits.", "Pin radius and nBits."),
        why: L("العتبات تاريخية داخل بروتوكول.", "Cutoffs are historical inside a protocol."),
      },
    ],
  },
];

export const graphNodes: GraphNode[] = [
  { id: "thermo", label: L("ثيرموديناميكا", "Thermodynamics"), group: "physics", lessonId: "l2-thermo" },
  { id: "affinity", label: L("ألفة", "Affinity"), group: "physics", lessonId: "l8-affinity" },
  { id: "fe", label: L("طاقة حرة", "Free energy"), group: "freeEnergy", lessonId: "l10-dg" },
  { id: "md", label: L("MD", "MD"), group: "md", lessonId: "l9-newton" },
  { id: "mmpbsa", label: L("MM/PBSA", "MM/PBSA"), group: "freeEnergy", lessonId: "l10-mmpbsa" },
  { id: "fep", label: L("FEP", "FEP"), group: "freeEnergy", lessonId: "l10-fep" },
  { id: "dock", label: L("التحام", "Docking"), group: "docking", lessonId: "l8-problem" },
  { id: "ff", label: L("حقل قوة", "Force field"), group: "mechanics", lessonId: "l6-etotal" },
  { id: "score", label: L("تقييم", "Scoring"), group: "docking", lessonId: "l8-scoring" },
  { id: "qsar", label: L("QSAR", "QSAR"), group: "lbdd", lessonId: "l12-qsar" },
  { id: "admet", label: L("ADMET", "ADMET"), group: "admet", lessonId: "l15-adme" },
  { id: "ml", label: L("تعلّم آلي", "ML"), group: "ml", lessonId: "l16-pipeline" },
];

export const graphEdges: GraphEdge[] = [
  { from: "thermo", to: "affinity", label: L("ΔG ↔ K", "ΔG ↔ K") },
  { from: "affinity", to: "fe", label: L("تعريف", "definition") },
  { from: "fe", to: "md", label: L("معاينة", "sampling") },
  { from: "fe", to: "mmpbsa", label: L("تقريب نهاية", "end-state approx.") },
  { from: "fe", to: "fep", label: L("مسار كيميائي", "alchemical path") },
  { from: "md", to: "mmpbsa", label: L("هيئات", "poses") },
  { from: "ff", to: "md", label: L("V(r)", "V(r)") },
  { from: "ff", to: "dock", label: L("فيزياء جزئية", "partial physics") },
  { from: "dock", to: "score", label: L("ترتيب", "ranking") },
  { from: "score", to: "affinity", label: L("ليس هو", "is not") },
  { from: "qsar", to: "admet", label: L("واصفات", "descriptors") },
  { from: "ml", to: "qsar", label: L("تعميم", "generalisation") },
  { from: "ml", to: "score", label: L("خطر الهيكل", "scaffold risk") },
];

export const challengeScenarios: { id: string; title: L10n; protocol: L10n; expert: L10n }[] = [
  {
    id: "ch-classic",
    title: L("البروتوكول الكلاسيكي الضعيف", "The classic weak protocol"),
    protocol: L(
      "بروتين من PDB. هيدروجين. التحام Vina. أفضل مركب لأن الدرجة −10.2 kcal/mol. 100 ns MD. RMSD استقر. إذن المركب دواء محتمل.",
      "Protein from the PDB. Hydrogens added. AutoDock Vina. Top compound because it scored −10.2 kcal/mol. 100 ns MD. RMSD stabilized. Therefore the compound is a potential drug.",
    ),
    expert: L(
      "مشكلات (≥15): لا PDB/جودة؛ لا دليل موقع؛ هيدروجين بلا pKa/توتومر؛ معادن/ماء؛ ستيريو ليغند؛ صندوق غير موثّق؛ −10.2 ليست ΔG؛ لا إعادة تحام؛ لا مخادعات/ROC؛ لا مرونة؛ 100 ns بلا نُسخ؛ RMSD مسطح ≠ تقارب؛ لا تفاعلات/خروج؛ لا حقل/ماء/thermostat؛ لا ADMET؛ لغة «دواء»؛ لا مُفنِّد؛ لا تخليق؛ لا إصدار؛ نتيجة منتقاة.",
      "Problems (≥15): no PDB/quality; no site evidence; hydrogens without pKa/tautomer; metals/water; ligand stereo; undocumented box; −10.2 is not ΔG; no redocking; no decoys/ROC; no flexibility; 100 ns no replicas; flat RMSD ≠ convergence; no contacts/unbinding; no FF/water/thermostat; no ADMET; “drug” language; no falsifier; no synthesis; no version; a selected outcome.",
    ),
  },
  {
    id: "ch-mmpbsa",
    title: L("جدول MM/PBSA كمقياس", "An MM/PBSA table as an assay"),
    protocol: L(
      "عشرة مركبات متباعدة، 20 ns لكل منها، جدول ΔG بثلاث خانات، ترتيب تخليق قاطع.",
      "Ten distant chemotypes, 20 ns each, a ΔG table to three decimals, categorical synthesis ranking.",
    ),
    expert: L(
      "خطأ أكبر من الفروق؛ إنتروبي ضعيف؛ لا نُسخ؛ خارج نطاق الطريقة؛ دقة زائفة؛ لا هيئة؛ لا تجربة؛ لا ADMET.",
      "Error larger than gaps; weak entropy; no replicas; outside the method; false precision; no poses; no assay; no ADMET.",
    ),
  },
  {
    id: "ch-ai",
    title: L("نموذج توليدي «اكتشف» جزيئاً", "A generative model that ‘discovered’ a molecule"),
    protocol: L(
      "تدريب على ChEMBL، جزيئات مولَّدة، IC50 متوقعة 12 nM بلا مقايسة وبلا نطاق.",
      "Trained on ChEMBL, generated molecules, predicted IC50 12 nM with no assay and no domain.",
    ),
    expert: L(
      "12 nM مختلق إن لم يُقس. تسرّب هياكل، لا صنع، لا ADMET، لا هدف بنيوي، لغة اكتشاف بلا دليل.",
      "12 nM is invented if unmeasured. Scaffold leakage, no makeability, no ADMET, no structural target, discovery language without evidence.",
    ),
  },
];

export const papersOfWeek: { id: string; title: L10n; cite: L10n; why: L10n }[] = [
  {
    id: "p1",
    title: L("AutoDock Vina", "AutoDock Vina"),
    cite: L(
      "Trott O, Olson AJ. Journal of Computational Chemistry, 2010. تحقّق من تفاصيل الاستشهاد قبل النقل.",
      "Trott O, Olson AJ. Journal of Computational Chemistry, 2010. Verify citation details before reuse.",
    ),
    why: L("اقرأ ما يعد به المحرّك وما لا يعد.", "Read what the engine promises and what it does not."),
  },
  {
    id: "p2",
    title: L("أدوار الحساب في الاكتشاف", "Roles of computation in discovery"),
    cite: L(
      "Jorgensen WL. Science, 2004. تحقّق قبل النقل.",
      "Jorgensen WL. Science, 2004. Verify before reuse.",
    ),
    why: L("خريطة متواضعة لقدرة الحساب.", "A modest map of what computation can do."),
  },
  {
    id: "p3",
    title: L("GROMACS", "GROMACS"),
    cite: L(
      "Abraham MJ et al. SoftwareX, 2015. تحقّق قبل النقل.",
      "Abraham MJ et al. SoftwareX, 2015. Verify before reuse.",
    ),
    why: L("المحرّك أداة؛ الحقل هو الفيزياء.", "The engine is a tool; the force field is the physics."),
  },
];

export const dailyQuestions = [
  {
    id: "dq1",
    prompt: L(
      "إن استقر RMSD عند 2.3 Å، هل تكتب «المعقّد مستقر»؟ لماذا؟",
      "If RMSD plateaus at 2.3 Å, may you write “the complex is stable”? Why?",
    ),
  },
  {
    id: "dq2",
    prompt: L("ما الذي يفعله exhaustiveness — وما الذي لا يفعله؟", "What does exhaustiveness do — and what does it not do?"),
  },
  {
    id: "dq3",
    prompt: L("لماذا قد يرتبط ليغند «ضعيف التفاعلات الظاهرة» بألفة عالية؟", "Why might a ligand with ‘weak-looking’ interactions still bind tightly?"),
  },
  {
    id: "dq4",
    prompt: L("ما الذي يُفنّد دراسة فرز قبل أن تبدأ؟", "What would falsify a screening study before it starts?"),
  },
];

export const frontierTopics: {
  id: string;
  title: L10n;
  status: "established" | "promising" | "emerging";
  body: L10n;
}[] = [
  { id: "f1", title: L("التوليد الجزيئي بالذكاء الاصطناعي", "AI molecular generation"), status: "promising", body: L("واعدة لتوسيع الأفكار. التوزيع المتعلَّم ليس كيمياء قابلة للصنع تلقائياً.", "Promising for idea expansion. A learned distribution is not automatically makeable chemistry.") },
  { id: "f2", title: L("نماذج لغة البروتين", "Protein language models"), status: "promising", body: L("تمثيلات مفيدة. ليست بديلاً عن هولو أو مقايسة.", "Useful representations. Not a substitute for a holo structure or an assay.") },
  { id: "f3", title: L("AlphaFold في التصميم", "AlphaFold in design"), status: "promising", body: L("طية متوقعة ≠ هيئة مرتبطة.", "A predicted fold ≠ a bound pose.") },
  { id: "f4", title: L("نماذج الانتشار الجزيئي", "Molecular diffusion models"), status: "emerging", body: L("نشطة بحثياً. تحتاج تحققاً كيميائياً قاسياً.", "Research-active. Need harsh chemical validation.") },
  { id: "f5", title: L("شبكات بيانية", "Graph neural networks"), status: "promising", body: L("تمثيل طبيعي. خطر تعلّم الهيكل.", "A natural representation. Risk of learning the scaffold.") },
  { id: "f6", title: L("دوال تقييم متعلَّمة", "Learned scoring functions"), status: "promising", body: L("قد تلتقط فيزياء أو انحياز قاعدة البيانات.", "May capture physics — or database bias.") },
  { id: "f7", title: L("طرائق الطاقة الحرة", "Free-energy methods"), status: "established", body: L("FEP/TI راسخة على أسئلة ضيقة بموارد كافية.", "FEP/TI are established on narrow questions with enough resource.") },
  { id: "f8", title: L("فرز واسع النطاق", "Ultra-large virtual screening"), status: "promising", body: L("المكتبات الهائلة تضاعف خطأ البروتوكول إن ضعف التحقق.", "Ultra-large libraries amplify protocol error if validation is weak.") },
];
