import type {
  CaseStudy,
  CommandEntry,
  Comparison,
  DictEntry,
  EquationEntry,
  Flashcard,
  GraphEdge,
  GraphNode,
  Mistake,
  Quiz,
  SoftwareLab,
  VivaQuestion,
} from "@/lib/academy/types";
import { L } from "@/lib/academy/content/helpers";

export const quizzes: Quiz[] = [
  {
    id: "q-l0",
    title: L("توجّه: ماذا يفعل الحساب وماذا لا يفعل", "Orientation: what computation does and does not do"),
    description: L("خلط الدرجة بالدواء هو الفشل الأول.", "Confusing a score with a drug is the first failure."),
    lessonId: "l0-cadd",
    questions: [
      {
        id: "q-l0-1",
        kind: "tf",
        prompt: L("درجة الالتحام تساوي طاقة الارتباط الحرة ΔG.", "A docking score equals the binding free energy ΔG."),
        answer: false,
        explanation: L("دالة التقييم تقريب بحث لترتيب poses. تفتقد معاينة كاملة، إنتروبي، وغالباً مذيباً صريحاً. ليست −RT ln K.", "A scoring function is a search heuristic for ranking poses. It lacks full sampling, entropy, and often explicit solvent. It is not −RT ln K."),
        difficulty: "beginner",
      },
      {
        id: "q-l0-2",
        kind: "mcq",
        prompt: L("أي عبارة تصف CADD بدقة؟", "Which sentence describes CADD accurately?"),
        options: [
          L("يُنتج أدوية جاهزة للتجارب السريرية.", "It produces drugs ready for clinical trials."),
          L("يُنتج نماذج وفرضيات تعتمد على افتراضات وتحقّق.", "It produces models and hypotheses that depend on assumptions and validation."),
          L("يغني عن الفحوص البيولوجية إذا كانت الدرجة < −10.", "It replaces biological assays if the score is < −10."),
          L("يقيس Kd مباشرة من PDB.", "It measures Kd directly from a PDB file."),
        ],
        answer: 1,
        explanation: L("الحساب فرضية منظّمة. السريري والفحص خارج نطاق الدرجة.", "Computation is organised hypothesis. The clinic and the assay sit outside the score."),
        difficulty: "beginner",
      },
      {
        id: "q-l0-3",
        kind: "critique",
        prompt: L("نقد: «أرسينا 5000 مركّب واخترنا الأفضل كمثبط واعد».", "Critique: 'We docked 5000 compounds and selected the best as a promising inhibitor.'"),
        answer: "The sentence treats rank as activity, skips pose chemistry, decoys, protonation, and any assay. At best it is a purchase list hypothesis.",
        explanation: L("الرتبة ليست نشاطاً. بلا كيمياء هيئة، بلا decoys، بلا برتنة، بلا فحص: قائمة شراء في أحسن الأحوال.", "Rank is not activity. Without pose chemistry, decoys, protonation, or an assay: a purchase list at best."),
        difficulty: "intermediate",
      },
      {
        id: "q-l0-4",
        kind: "tf",
        prompt: L("RMSD المسطح في محاكاة واحدة يثبت أن الليجند دواء.", "A flat RMSD in one simulation proves the ligand is a drug."),
        answer: false,
        explanation: L("حتى استقرار هندسي لا يعني تقارباً ولا فعالية بيولوجية.", "Even geometric quiet is not convergence and not biological efficacy."),
        difficulty: "beginner",
      },
      {
        id: "q-l0-5",
        kind: "mcq",
        prompt: L("أين ينجح الحساب غالباً كأداة؟", "Where does computation usually succeed as a tool?"),
        options: [
          L("استبدال التجربة السريرية.", "Replacing a clinical experiment."),
          L("ترتيب فرضيات SAR وتفسير بنى مع تحفّظ.", "Ranking SAR hypotheses and interpreting structures with caveats."),
          L("قياس IC50 من الصورة.", "Measuring IC50 from a picture."),
          L("إثبات السلامة.", "Proving safety."),
        ],
        answer: 1,
        explanation: L("قيمته في تقليل التجارب الغبية وتوضيح الفرضيات لا في الشهادات العلاجية.", "Its value is fewer stupid experiments and clearer hypotheses, not therapeutic certificates."),
        difficulty: "intermediate",
      },
      {
        id: "q-l0-6",
        kind: "short",
        prompt: L("اذكر حدّين فيزيائيين يجعلان النموذج يكذب حتى لو كان البرنامج صحيحاً.", "Name two physical limits that make a model lie even if the software is correct."),
        answer: "Incomplete sampling; approximate potential (missing polarizability/reactivity, continuum water, etc.).",
        explanation: L("معاينة ناقصة وجهد تقريبي (بدون استقطاب/تفاعلية، ماء مستمر، …) يكذبان بأمانة حسابية.", "Incomplete sampling and an approximate potential (no polarizability/reactivity, continuum water, …) lie with computational honesty."),
        difficulty: "advanced",
      },
    ],
  },
  {
    id: "q-l1",
    title: L("توتومر وبرتنة", "Tautomer and protonation"),
    description: L("خطأ تحضير يُفسد خط الالتحام كاملاً.", "A preparation error wrecks the whole docking line."),
    lessonId: "l1-tautomer",
    questions: [
      {
        id: "q-l1-1",
        kind: "tf",
        prompt: L("رسم الليجند كما جاء من المورّد يضمن الحالة الصحيحة عند pH 7.4.", "Drawing the ligand as supplied by the vendor guarantees the correct state at pH 7.4."),
        answer: false,
        explanation: L("المورّد قد يعطي حمضاً محايداً أو ملحاً أو توتومراً بلورياً. الجيب وpH الفحص يقرران.", "The vendor may give a neutral acid, a salt, or a crystal tautomer. The pocket and assay pH decide."),
        difficulty: "beginner",
      },
      {
        id: "q-l1-2",
        kind: "mcq",
        prompt: L("أمين أليفاتي pKa ≈ 9.8 عند pH 7.4 غالباً:", "An aliphatic amine with pKa ≈ 9.8 at pH 7.4 is usually:"),
        options: [
          L("محايد.", "Neutral."),
          L("مبرتن (موجب).", "Protonated (positive)."),
          L("سالب.", "Negative."),
          L("غير موجود في الماء.", "Absent in water."),
        ],
        answer: 1,
        explanation: L("قاعدة أقوى من 7.4 بوضوح تبقى في الغالب BH+ في الماء.", "A base clearly stronger than 7.4 remains mostly BH+ in water."),
        difficulty: "intermediate",
      },
      {
        id: "q-l1-3",
        kind: "critique",
        prompt: L("نقد: أُرسي الهيستيدين دائماً كـ HID دون النظر إلى الجيب.", "Critique: histidine is always docked as HID without looking at the pocket."),
        answer: "Histidine tautomer/protonation is environment-dependent; HID-by-default can destroy a salt bridge or create a false clash.",
        explanation: L("توتومر/برتنة His تعتمد على البيئة. HID الافتراضي قد يكسر salt bridge أو يصنع clash.", "His tautomer/protonation depends on environment. Default HID may break a salt bridge or create a clash."),
        difficulty: "advanced",
      },
      {
        id: "q-l1-4",
        kind: "tf",
        prompt: L("التوتومران لـ keto-enol لهما نفس البصمة ثنائية الأبعاد دائماً وبالتالي نفس الالتحام.", "Keto-enol tautomers always share the same 2D fingerprint and therefore the same docking."),
        answer: false,
        explanation: L("قد تتشابه البصمات وتختلف مانحات H-bond ومتجهات الالتحام جذرياً.", "Fingerprints may look similar while H-bond donors and docking vectors differ sharply."),
        difficulty: "intermediate",
      },
      {
        id: "q-l1-5",
        kind: "short",
        prompt: L("لماذا يُعد خطأ البرتنة أخطر من exhaustiveness منخفض؟", "Why is a protonation error more dangerous than low exhaustiveness?"),
        answer: "Wrong charge changes the physical Hamiltonian of the pose; low exhaustiveness is incomplete search of the right physics.",
        explanation: L("الشحنة الخاطئة تغيّر هاميلتون الهيئة. exhaustiveness المنخفض بحث ناقص في الفيزياء الصحيحة.", "Wrong charge changes the pose Hamiltonian. Low exhaustiveness is incomplete search of the right physics."),
        difficulty: "researcher",
      },
    ],
  },
  {
    id: "q-l2",
    title: L("غيبس والاتزان", "Gibbs and equilibrium"),
    description: L("ΔG = −RT ln K لغة الارتباط.", "ΔG = −RT ln K is the language of binding."),
    lessonId: "l2-gibbs",
    questions: [
      {
        id: "q-l2-1",
        kind: "tf",
        prompt: L("ΔG سالب أكبر يعني ارتباطاً أقوى عند نفس T وبنفس تعريف المعيار.", "A more negative ΔG means tighter binding at the same T and the same standard state."),
        answer: true,
        explanation: L("من ΔG = −RT ln K، K أكبر حين ΔG أكثر سلبية، بشرط نفس الحالة المعيارية.", "From ΔG = −RT ln K, K is larger when ΔG is more negative, given the same standard state."),
        difficulty: "beginner",
      },
      {
        id: "q-l2-2",
        kind: "mcq",
        prompt: L("Kd صغير جداً يعني:", "A very small Kd means:"),
        options: [
          L("ارتباطاً ضعيفاً.", "Weak binding."),
          L("ارتباطاً قوياً عند الاتزان (مع ثبات الشروط).", "Tight equilibrium binding (conditions fixed)."),
          L("koff سريعاً بالضرورة.", "Necessarily fast koff."),
          L("أن المركب دواء.", "That the compound is a drug."),
        ],
        answer: 1,
        explanation: L("Kd = koff/kon عند أبسط نموذج. صغر Kd لا يحدد السرعة المطلقة ولا السلامة.", "Kd = koff/kon in the simplest model. A small Kd does not set absolute rates or safety."),
        difficulty: "intermediate",
      },
      {
        id: "q-l2-3",
        kind: "calc",
        prompt: L("نوعياً: إن تضاعفت K عشر مرات عند ثبات T، ماذا يحدث لـ ΔG؟ (إشارة واتجاه)", "Qualitatively: if K increases ten-fold at fixed T, what happens to ΔG? (sign and direction)"),
        answer: "ΔG becomes more negative by RT ln 10 (about 1.4 kcal/mol at 298 K as an order-of-magnitude reminder, not a lab measurement).",
        explanation: L("ΔΔG = −RT ln(10). عند ~298 K هذا في حدود 1.4 kcal/mol كمقياس رتبة لا كقياس مختبر.", "ΔΔG = −RT ln(10). Near 298 K that is ~1.4 kcal/mol as an order of magnitude, not a lab measurement."),
        difficulty: "advanced",
      },
      {
        id: "q-l2-4",
        kind: "tf",
        prompt: L("IC50 يساوي دائماً Kd.", "IC50 always equals Kd."),
        answer: false,
        explanation: L("IC50 يعتمد على تركيز الركيزة وبروتوكول الفحص. Cheng–Prusoff يربطهما بشروط.", "IC50 depends on substrate concentration and assay protocol. Cheng–Prusoff links them under assumptions."),
        difficulty: "intermediate",
      },
      {
        id: "q-l2-5",
        kind: "critique",
        prompt: L("نقد: تحويل درجة Vina −9.2 مباشرة إلى nanomolar Kd في الخلاصة.", "Critique: converting a Vina score of −9.2 directly into a nanomolar Kd in the abstract."),
        answer: "Unit abuse: a scoring function is not −RT ln K and is not calibrated as experimental Kd.",
        explanation: L("إساءة وحدات: دالة التقييم ليست −RT ln K ولا معايرة كـ Kd تجريبي.", "Unit abuse: the scoring function is not −RT ln K and is not calibrated as experimental Kd."),
        difficulty: "researcher",
      },
      {
        id: "q-l2-6",
        kind: "short",
        prompt: L("ما دور الحالة المعيارية في مقارنة ΔG؟", "What role does the standard state play in comparing ΔG?"),
        answer: "K and ΔG are defined relative to a concentration standard (often 1 M). Changing it changes the number without changing physics.",
        explanation: L("K وΔG يُعرَّفان نسبة إلى معيار تركيز (غالباً 1 M). تغييره يغيّر الرقم لا الفيزياء.", "K and ΔG are defined relative to a concentration standard (often 1 M). Changing it changes the number, not the physics."),
        difficulty: "professor",
      },
    ],
  },
  {
    id: "q-l3",
    title: L("تدرجات وقوى", "Gradients and forces"),
    description: L("F = −∇V قلب المحاكاة.", "F = −∇V is the heart of simulation."),
    lessonId: "l3-gradients",
    questions: [
      {
        id: "q-l3-1",
        kind: "tf",
        prompt: L("القوة على ذرة هي سالب تدرج الجهد عند تلك الإحداثيات.", "The force on an atom is minus the gradient of the potential at those coordinates."),
        answer: true,
        explanation: L("هذا تعريف الميكانيكا المحافظة المستخدمة في MM/MD.", "That is the conservative-mechanics definition used in MM/MD."),
        difficulty: "beginner",
      },
      {
        id: "q-l3-2",
        kind: "mcq",
        prompt: L("خطوة زمنية أكبر مما يسمح به أسرع طور (روابط H) تؤدي غالباً إلى:", "A timestep larger than the fastest mode (H-bonds) allows usually leads to:"),
        options: [
          L("تقارب أفضل.", "Better convergence."),
          L("عدم استقرار عددي / انفجار طاقة.", "Numerical instability / energy explosion."),
          L("ΔG أدق.", "More accurate ΔG."),
          L("إلغاء الحاجة للقيود.", "No need for constraints."),
        ],
        answer: 1,
        explanation: L("المكامل يفشل حين لا تُحل التذبذبات السريعة. لذلك ~2 fs مع قيود هيدروجين شائع.", "The integrator fails when fast oscillations are unresolved. Hence ~2 fs with hydrogen constraints is common."),
        difficulty: "intermediate",
      },
      {
        id: "q-l3-3",
        kind: "tf",
        prompt: L("5 fs بدون قيود مناسبة خيار آمن لكل بروتين-ليغند.", "5 fs without appropriate constraints is a safe default for every protein–ligand system."),
        answer: false,
        explanation: L("بلا قيود أو كتلة مهدرجة مدروسة، 5 fs غالباً غير آمن. لا تُنسخ كموضة.", "Without constraints or a careful hydrogen-mass repartition, 5 fs is often unsafe. Do not copy it as fashion."),
        difficulty: "intermediate",
      },
      {
        id: "q-l3-4",
        kind: "short",
        prompt: L("لماذا نحتاج تكاملاً عددياً أصلاً في MD؟", "Why is numerical integration needed in MD at all?"),
        answer: "Newton's equations for many-body potentials have no closed-form trajectory; we step forces in time.",
        explanation: L("معادلات نيوتن لجهد كثير الجسيمات بلا مسار مغلق الشكل؛ نخطو القوى في الزمن.", "Newton's equations for many-body potentials have no closed-form trajectory; we step forces in time."),
        difficulty: "advanced",
      },
      {
        id: "q-l3-5",
        kind: "critique",
        prompt: L("نقد: «استخدمنا انحداراً حاداً 50 خطوة إذن البنية في الحد الأدنى العالمي».", "Critique: 'We used 50 steps of steepest descent so the structure is at the global minimum.'"),
        answer: "Local relaxation only; no global guarantee; 50 steps may not even finish local clashes.",
        explanation: L("استرخاء محلي فقط بلا ضمان عالمي؛ 50 خطوة قد لا تنهي حتى الاصطدامات المحلية.", "Local relaxation only; no global guarantee; 50 steps may not even finish local clashes."),
        difficulty: "researcher",
      },
    ],
  },
  {
    id: "q-l4",
    title: L("جيوب وجودة بنية", "Pockets and structure quality"),
    description: L("الجيب قرار قبل الصندوق.", "The pocket is a decision before the box."),
    lessonId: "l4-pockets",
    questions: [
      {
        id: "q-l4-1",
        kind: "tf",
        prompt: L("كل تجويف هندسي في البروتين موقع ارتباط دوائي.", "Every geometric cavity in a protein is a drug-binding site."),
        answer: false,
        explanation: L("كثير من التجاويف بلورية أو غير ligandable. الدليل: ليغند، عائلة، أو تجربة.", "Many cavities are crystal artifacts or not ligandable. Evidence: a ligand, the family, or an experiment."),
        difficulty: "beginner",
      },
      {
        id: "q-l4-2",
        kind: "mcq",
        prompt: L("B-factor مرتفع في عروة الجيب يعني غالباً:", "A high B-factor in a pocket loop usually means:"),
        options: [
          L("أن العروة جدار صلب مثالي للالتحام الجامد.", "The loop is a rigid wall ideal for rigid docking."),
          L("اضطراباً/مرونة في البلورة يجب أن تُدخل في تفسير الهيئة.", "Disorder/flexibility in the crystal that must enter pose interpretation."),
          L("أن AlphaFold سيُصلحها تلقائياً.", "That AlphaFold will automatically fix it."),
          L("أن الماء غير مهم.", "That water is irrelevant."),
        ],
        answer: 1,
        explanation: L("B-factor اضطراب نموذجي/بلوري. ليس RMSF محلول، لكنه إنذار مرونة.", "B-factor is model/crystal disorder. Not solution RMSF, but a flexibility alarm."),
        difficulty: "intermediate",
      },
      {
        id: "q-l4-3",
        kind: "tf",
        prompt: L("طية AlphaFold تساوي bound pose.", "An AlphaFold fold equals a bound pose."),
        answer: false,
        explanation: L("الطية المتوقعة ليست هيئة مرتبطة بليغند. الجيب قد يكون مغلقاً والعُرى ضعيفة الثقة.", "A predicted fold is not a ligand-bound conformation. The pocket may be closed and loops low-confidence."),
        difficulty: "beginner",
      },
      {
        id: "q-l4-4",
        kind: "critique",
        prompt: L("نقد: حذف كل المياه والمعادن قبل الالتحام «للتبسيط».", "Critique: deleting all waters and metals before docking 'for simplicity'."),
        answer: "May delete the physics (bridging water, catalytic metal). Document keep/delete per site.",
        explanation: L("قد يحذف الفيزياء (ماء جسري، معدن تحفيزي). وثّق الإبقاء/الحذف لكل موقع.", "May delete the physics (bridging water, catalytic metal). Document keep/delete per site."),
        difficulty: "advanced",
      },
      {
        id: "q-l4-5",
        kind: "short",
        prompt: L("اذكر مؤشرين لجودة بلورة قبل أن ترسّم.", "Name two crystal-quality indicators before you dock."),
        answer: "Resolution; ligand density/occupancy/B-factor; missing loops in the pocket (any two).",
        explanation: L("resolution؛ كثافة/occupancy/B-factor لليغند؛ عُرى ناقصة في الجيب.", "Resolution; ligand density/occupancy/B-factor; missing pocket loops."),
        difficulty: "intermediate",
      },
    ],
  },
  {
    id: "q-l5",
    title: L("بصمات وتانيموتو", "Fingerprints and Tanimoto"),
    description: L("0.7 ليست ثابت طبيعة.", "0.7 is not a constant of nature."),
    lessonId: "l5-fp",
    questions: [
      {
        id: "q-l5-1",
        kind: "tf",
        prompt: L("Tanimoto 0.7 على أي بصمة يعني نفس النشاط.", "Tanimoto 0.7 on any fingerprint means the same activity."),
        answer: false,
        explanation: L("العتبة تعتمد على البصمة والكيمياء. activity cliffs تكسر المبدأ محلياً.", "The cutoff depends on fingerprint and chemistry. Activity cliffs break the principle locally."),
        difficulty: "beginner",
      },
      {
        id: "q-l5-2",
        kind: "mcq",
        prompt: L("بصمة Morgan radius 2 تمثّل أساساً:", "A Morgan radius-2 fingerprint mainly represents:"),
        options: [
          L("هيئة 3D المرتبطة.", "The bound 3D pose."),
          L("بيئات ذرية دائرية ثنائية الأبعاد.", "Circular 2D atom environments."),
          L("طاقة الارتباط.", "Binding energy."),
          L("logD المقيس.", "Measured logD."),
        ],
        answer: 1,
        explanation: L("دوائر حول الذرات في الرسم 2D، لا الوضع البلوري.", "Circles around atoms in the 2D graph, not the crystal pose."),
        difficulty: "intermediate",
      },
      {
        id: "q-l5-3",
        kind: "short",
        prompt: L("اكتب صيغة Tanimoto لبصمتين ثنائيتين A وB.", "Write the Tanimoto formula for two binary fingerprints A and B."),
        answer: "T = |A∩B| / |A∪B|",
        explanation: L("نسبة التقاطع إلى الاتحاد للبتات المشتعلة.", "Intersection over union of on-bits."),
        difficulty: "beginner",
      },
      {
        id: "q-l5-4",
        kind: "critique",
        prompt: L("نقد: مكتبة مليئة بنظائر تُظهر إثراء docking ممتازاً.", "Critique: an analogue-heavy library shows excellent docking enrichment."),
        answer: "Redundant chemotypes inflate enrichment; report scaffold diversity and a hard decoy set.",
        explanation: L("الكيمياء المكررة تُنفخ الإثراء. أبلغ تنوع الـ scaffold ومجموعة خداع صعبة.", "Redundant chemistry inflates enrichment. Report scaffold diversity and a hard decoy set."),
        difficulty: "advanced",
      },
      {
        id: "q-l5-5",
        kind: "tf",
        prompt: L("تغيير nBits دون ذكره يسمح بمقارنة عتبات المشروع التاريخية.", "Changing nBits without reporting it still allows comparison to the project's historical cutoffs."),
        answer: false,
        explanation: L("nBits جزء من تعريف البصمة بسبب تصادم البتات.", "nBits is part of the fingerprint definition because of bit collisions."),
        difficulty: "intermediate",
      },
    ],
  },
  {
    id: "q-l6",
    title: L("دالة الجهد", "The potential"),
    description: L("كل حد قرار فيزيائي.", "Each term is a physics decision."),
    lessonId: "l6-etotal",
    questions: [
      {
        id: "q-l6-1",
        kind: "tf",
        prompt: L("الميكانيكا الجزيئية الكلاسيكية تكسر الروابط التساهمية تلقائياً في المسار العادي.", "Classical molecular mechanics spontaneously breaks covalent bonds on an ordinary trajectory."),
        answer: false,
        explanation: L("حدود bonded توافقية/فورييه لا تسمح بتفاعل كيميائي حقيقي ما لم تُستخدم نماذج تفاعل خاصة.", "Harmonic/Fourier bonded terms do not allow true chemistry unless a specialised reactive model is used."),
        difficulty: "beginner",
      },
      {
        id: "q-l6-2",
        kind: "mcq",
        prompt: L("حدّ لينارد-جونز r⁻¹² يمثّل أساساً:", "The Lennard-Jones r⁻¹² term mainly represents:"),
        options: [
          L("تجاذب تشتتي مشتق من ميكانيكا الكم الدقيقة.", "Dispersion attraction derived from exact QM."),
          L("طرداً تجريبياً قصير المدى.", "Short-range empirical repulsion."),
          L("شحنة جزئية.", "Partial charge."),
          L("قيود SHAKE.", "SHAKE constraints."),
        ],
        answer: 1,
        explanation: L("r⁻¹² شكل مريح للطرد؛ r⁻⁶ تشتت تقريبي.", "r⁻¹² is a convenient repulsive form; r⁻⁶ is approximate dispersion."),
        difficulty: "intermediate",
      },
      {
        id: "q-l6-3",
        kind: "short",
        prompt: L("لماذا الشحنة الجزئية في MM ليست ملاحظة تجريبية مباشرة؟", "Why is a partial charge in MM not a direct experimental observable?"),
        answer: "Charge is a model parameter fit to reproduce electrostatics (e.g. ESP); it is not uniquely defined by QM or experiment.",
        explanation: L("الشحنة معامل نموذج يُضبط لإعادة إنتاج الكهروستاتيك (مثل ESP)؛ ليست وحيدة التعريف كمّياً أو تجريبياً.", "Charge is a model parameter fit to electrostatics (e.g. ESP); it is not uniquely defined by QM or experiment."),
        difficulty: "advanced",
      },
      {
        id: "q-l6-4",
        kind: "tf",
        prompt: L("خلط حقل بروتين مع ليغند بشحنة من فلسفة مختلفة آمن دائماً.", "Mixing a protein field with a ligand charged under a different philosophy is always safe."),
        answer: false,
        explanation: L("electrostatics تصبح بلا مقياس مشترك. وثّق مسار الشحن.", "Electrostatics lose a common scale. Document the charge path."),
        difficulty: "intermediate",
      },
      {
        id: "q-l6-5",
        kind: "critique",
        prompt: L("نقد: «استخدمنا GAFF إذن النتائج كمية كالتجربة».", "Critique: 'We used GAFF so the results are as quantitative as experiment.'"),
        answer: "GAFF is a general ligand field with limits (polarization, unusual chemistry). It is not experimental thermodynamics.",
        explanation: L("GAFF حقل ليغند عام بحدود (استقطاب، كيمياء غير معتادة). ليس ثيرموديناميكا تجريبية.", "GAFF is a general ligand field with limits (polarization, unusual chemistry). It is not experimental thermodynamics."),
        difficulty: "researcher",
      },
      {
        id: "q-l6-6",
        kind: "mcq",
        prompt: L("TIP3P هو:", "TIP3P is:"),
        options: [
          L("دالة تقييم التحام.", "A docking scoring function."),
          L("نموذج ماء بثلاث مواقع شائعة الاستخدام.", "A three-site water model in common use."),
          L("خوارزمية عنقدة.", "A clustering algorithm."),
          L("مقياس ADMET.", "An ADMET metric."),
        ],
        answer: 1,
        explanation: L("نموذج ماء صريح بثلاث مواقع؛ التوافق مع حقل البروتين قرار.", "An explicit three-site water model; compatibility with the protein field is a decision."),
        difficulty: "beginner",
      },
    ],
  },
  {
    id: "q-l8",
    title: L("التحام: بحث + درجة", "Docking: search + score"),
    description: L("الدرجة ليست ΔG.", "The score is not ΔG."),
    lessonId: "l8-not-dg",
    questions: [
      {
        id: "q-l8-1",
        kind: "tf",
        prompt: L("الالتحام محاكاة ارتباط كاملة في المذيب.", "Docking is a full binding simulation in solvent."),
        answer: false,
        explanation: L("بحث وضع في جيب غالباً مجمّد + دالة تقييم. ليست معاينة ΔG.", "Pose search in an often-frozen pocket plus a scoring function. Not ΔG sampling."),
        difficulty: "beginner",
      },
      {
        id: "q-l8-2",
        kind: "mcq",
        prompt: L("exhaustiveness في Vina يتحكم أساساً بـ:", "exhaustiveness in Vina mainly controls:"),
        options: [
          L("دقة ΔG المطلقة.", "Absolute ΔG accuracy."),
          L("مدى البحث العشوائي/إعادة المحاولات.", "How thoroughly the stochastic search is repeated."),
          L("حجم الصندوق تلقائياً.", "Box size automatically."),
          L("برتنة الليجند.", "Ligand protonation."),
        ],
        answer: 1,
        explanation: L("يزيد جهد البحث لا يحوّل الدرجة إلى طاقة حرارية.", "It increases search effort; it does not turn the score into free energy."),
        difficulty: "intermediate",
      },
      {
        id: "q-l8-3",
        kind: "critique",
        prompt: L("نقد: اختيار الوضعية ذات −10.2 kcal/mol كدليل nanomolar.", "Critique: picking the pose with −10.2 kcal/mol as nanomolar evidence."),
        answer: "Educational score-to-Kd leap: units look thermodynamic but the function is empirical/search-based; no assay, no redocking, no protonation audit.",
        explanation: L("قفزة تعليمية من درجة إلى Kd: الوحدات تشبه الثيرموديناميكا والدالة تجريبية/بحثية. بلا فحص ولا redocking ولا تدقيق برتنة.", "Educational score-to-Kd leap: units look thermodynamic but the function is empirical/search-based. No assay, redocking, or protonation audit."),
        difficulty: "advanced",
      },
      {
        id: "q-l8-4",
        kind: "tf",
        prompt: L("نجاح redocking لليغند المعروف يضمن أن الفرز سيُثري actives جديدة.", "Successful redocking of the known ligand guarantees that the screen will enrich new actives."),
        answer: false,
        explanation: L("redocking لازم غير كافٍ. الإثراء يحتاج decoys وكيمياء متنوعة.", "Redocking is necessary but not sufficient. Enrichment needs decoys and diverse chemistry."),
        difficulty: "intermediate",
      },
      {
        id: "q-l8-5",
        kind: "short",
        prompt: L("لماذا قد تفوز الجزيئات الكبيرة الدهنية في الترتيب؟", "Why might large greasy molecules win the ranking?"),
        answer: "Many scoring functions reward buried hydrophobic contact and size without fully paying desolvation/entropy.",
        explanation: L("كثير من الدوال تكافئ التماس الكاره للماء والحجم دون دفع كامل لـ desolvation/entropy.", "Many functions reward buried hydrophobic contact and size without fully paying desolvation/entropy."),
        difficulty: "advanced",
      },
      {
        id: "q-l8-6",
        kind: "mcq",
        prompt: L("أفضل استخدام دفاعي لدرجة الالتحام:", "The most defensible use of a docking score:"),
        options: [
          L("Kd منشور.", "A published Kd."),
          L("ترتيب داخل فرضية هيئة بعد مرشحات كيميائية.", "Ranking inside a pose hypothesis after chemical filters."),
          L("إثبات سلامة hERG.", "Proving hERG safety."),
          L("استبدال FEP دائماً.", "Always replacing FEP."),
        ],
        answer: 1,
        explanation: L("رتبة مشروطة بفيزياء الهيئة لا كالوري مطلق.", "A rank conditional on pose physics, not absolute calories."),
        difficulty: "researcher",
      },
    ],
  },
  {
    id: "q-l9",
    title: L("MD وتقارب", "MD and convergence"),
    description: L("الطول لا يشتري الإحصاء.", "Length does not buy statistics."),
    lessonId: "l9-rmsd",
    questions: [
      {
        id: "q-l9-1",
        kind: "tf",
        prompt: L("RMSD يستقر عند 2.3 Å — هل المحاكاة متقاربة؟", "RMSD stabilizes at 2.3 Å — is the simulation converged?"),
        answer: false,
        explanation: L("استقرار مقياس هندسي واحد في مسار (أو نسخة) واحدة يعني غالباً البقاء في حوض محلي، لا اكتمال المعاينة. التقارب يتطلب نُسخاً مستقلة، observables أخرى (ملامسات، Rg)، ومتوسط كتل/عدم يقين. 2.3 Å رقم تعليمي لا عتبة سحرية. حتى المسار الهادئ قد يغادر لاحقاً، وقد يكون الليجند غادر الجيب بينما بقي RMSD البروتين مسطحاً إن أُسيئت المحاذاة.", "A plateau of one geometric metric on one trajectory (or replica) usually means staying in a local basin, not complete sampling. Convergence needs independent replicas, other observables (contacts, Rg), and block averaging/uncertainty. 2.3 Å is an educational number, not a magic cutoff. A quiet trace may leave later, and the ligand may have left the pocket while protein RMSD stays flat if alignment is misused."),
        difficulty: "intermediate",
      },
      {
        id: "q-l9-2",
        kind: "mcq",
        prompt: L("أقوى استثمار إحصائي لسؤال استقرار الهيئة غالباً:", "The statistically strongest investment for a pose-stability question is often:"),
        options: [
          L("نسخة واحدة طويلة جداً على لابتوب.", "One very long laptop replica."),
          L("عدة نُسخ مستقلة بعد اتزان معلن.", "Several independent replicas after declared equilibration."),
          L("تنعيم RMSD حتى يبدو أفقياً.", "Smoothing RMSD until it looks flat."),
          L("حذف النسخة التي انفصل فيها الليجند.", "Deleting the replica where the ligand left."),
        ],
        answer: 1,
        explanation: L("الاستقلال يكشف الأحواض. حذف الفاشل تحيز.", "Independence reveals basins. Deleting the failure is bias."),
        difficulty: "intermediate",
      },
      {
        id: "q-l9-3",
        kind: "tf",
        prompt: L("PME يتعامل مع electrostatics طويلة المدى تحت حدود دورية.", "PME handles long-range electrostatics under periodic boundaries."),
        answer: true,
        explanation: L("Particle Mesh Ewald طريقة شائعة لمجموع كولوم الدوري.", "Particle Mesh Ewald is a common method for the periodic Coulomb sum."),
        difficulty: "beginner",
      },
      {
        id: "q-l9-4",
        kind: "critique",
        prompt: L("نقد: 100 ns بلا نُسخ تُفسَّر كبرهان أن المركب يبقى مرتبطاً في الخلية.", "Critique: 100 ns with no replicas interpreted as proof the compound stays bound in cells."),
        answer: "Wrong ensemble, no cellular physics, n=1 sampling, timescale may miss unbinding; educational short-MD-as-proof pattern.",
        explanation: L("ensemble خاطئ، بلا فيزياء خلوية، n=1، والزمن قد يفوّت الانفصال: نمط MD القصير كبرهان.", "Wrong ensemble, no cellular physics, n=1, and the timescale may miss unbinding: the short-MD-as-proof pattern."),
        difficulty: "advanced",
      },
      {
        id: "q-l9-5",
        kind: "short",
        prompt: L("لماذا نحاذي backbone قبل RMSD الليجند؟", "Why align backbone before ligand RMSD?"),
        answer: "To remove protein rigid-body drift and measure ligand motion relative to the pocket.",
        explanation: L("لإزالة انجراف الجسم الصلب للبروتين وقياس حركة الليجند نسبة إلى الجيب.", "To remove protein rigid-body drift and measure ligand motion relative to the pocket."),
        difficulty: "intermediate",
      },
      {
        id: "q-l9-6",
        kind: "mcq",
        prompt: L("Berendsen thermostat في الإنتاج:", "Berendsen thermostat in production:"),
        options: [
          L("اختيار بلا أسئلة دائماً.", "Always unquestioned."),
          L("قد يُنتقد لأنه يضعف تقلبات الـ ensemble الصحيح؛ يُختار بوعي.", "May be criticised for damping proper ensemble fluctuations; choose consciously."),
          L("يحسب ΔG مباشرة.", "Computes ΔG directly."),
          L("بديل عن القيود.", "A substitute for constraints."),
        ],
        answer: 1,
        explanation: L("بعض المنظمات أصلح للاتزان منها للإنتاج. دافع أو غيّر.", "Some thermostats fit equilibration better than production. Defend or change."),
        difficulty: "researcher",
      },
    ],
  },
  {
    id: "q-l10",
    title: L("MM/PBSA وحدوده", "MM/PBSA and its limits"),
    description: L("تقدير لا Kd.", "An estimate, not a Kd."),
    lessonId: "l10-mmpbsa",
    questions: [
      {
        id: "q-l10-1",
        kind: "tf",
        prompt: L("MM/PBSA يقيس ΔG التجريبي مباشرة.", "MM/PBSA measures experimental ΔG directly."),
        answer: false,
        explanation: L("تقدير من مسار MM ومذيب مستمر، بأخطاء إلغاء ناقصة.", "An estimate from an MM trajectory and continuum solvent, with imperfect error cancellation."),
        difficulty: "beginner",
      },
      {
        id: "q-l10-2",
        kind: "mcq",
        prompt: L("الاستخدام الأكثر دفاعية:", "The most defensible use:"),
        options: [
          L("ترتيب scaffolds متباعدة كالوريّاً.", "Ranking distant scaffolds in calories."),
          L("إشارة داخل سلسلة متقاربة مع تشتت نُسخ.", "A hint inside a close series with replica scatter."),
          L("تحويل إلى IC50 خلوي.", "Conversion to cellular IC50."),
          L("إثبات آلية سريرية.", "Proof of a clinical mechanism."),
        ],
        answer: 1,
        explanation: L("خطأ الطريقة قد يتجاوز الفرق بين chemotypes المتباعدة.", "Method error may exceed gaps between distant chemotypes."),
        difficulty: "intermediate",
      },
      {
        id: "q-l10-3",
        kind: "critique",
        prompt: L("نقد: جدول −34.12 kcal/mol بلا ± وبلا نُسخ.", "Critique: a table of −34.12 kcal/mol with no ± and no replicas."),
        answer: "False precision; report scatter and do not over-decimal. Educational MM/PBSA-abuse pattern.",
        explanation: L("دقة زائفة؛ انشر التشتت ولا تُفرط في الخانات. نمط إساءة MM/PBSA التعليمي.", "False precision; publish scatter and do not over-decimal. Educational MM/PBSA-abuse pattern."),
        difficulty: "advanced",
      },
      {
        id: "q-l10-4",
        kind: "short",
        prompt: L("لماذا الماء المحبوس مشكلة لـ PB/GB؟", "Why is trapped water a problem for PB/GB?"),
        answer: "Continuum solvent poorly represents discrete bridging waters that are part of the pharmacophore.",
        explanation: L("المذيب المستمر يُضعف تمثيل مياه جسرية متقطعة هي جزء من pharmacophore.", "Continuum solvent poorly represents discrete bridging waters that are part of the pharmacophore."),
        difficulty: "advanced",
      },
      {
        id: "q-l10-5",
        kind: "tf",
        prompt: L("تفكيك الطاقة لكل بقايا برهان سببي قاطع.", "Per-residue energy decomposition is conclusive causal proof."),
        answer: false,
        explanation: L("مؤشر تصميم حسّاس للبروتوكول لا برهان تدخل سببي.", "A protocol-sensitive design hint, not causal intervention proof."),
        difficulty: "intermediate",
      },
    ],
  },
  {
    id: "q-l12",
    title: L("QSAR والنطاق", "QSAR and domain"),
    description: L("خارج النطاق تخمين.", "Outside the domain is a guess."),
    lessonId: "l12-qsar",
    questions: [
      {
        id: "q-l12-1",
        kind: "tf",
        prompt: L("التنبؤ خارج applicability domain تخمين حتى لو طُبع رقم.", "A prediction outside the applicability domain is a guess even if a number is printed."),
        answer: true,
        explanation: L("الخطأ غير معاير خارج خبرة التدريب. AD إلزامي.", "Error is uncalibrated outside training experience. AD is mandatory."),
        difficulty: "beginner",
      },
      {
        id: "q-l12-2",
        kind: "mcq",
        prompt: L("التقسيم الأصدق لسلسلة كيميائية غالباً:", "The more honest split for a chemical series is often:"),
        options: [
          L("عشوائي فقط.", "Random only."),
          L("scaffold أو زمني.", "Scaffold or temporal."),
          L("وضع كل النظائر في الاختبار.", "Putting all analogues in the test set."),
          L("بدون اختبار إذا R² التدريب 0.99.", "No test if training R² is 0.99."),
        ],
        answer: 1,
        explanation: L("العشوائي يسرب التوائم البنيوية.", "Random splits leak structural twins."),
        difficulty: "intermediate",
      },
      {
        id: "q-l12-3",
        kind: "tf",
        prompt: L("وزن TPSA في نموذج خطي خريطة للجيب.", "A TPSA weight in a linear model is a map of the pocket."),
        answer: false,
        explanation: L("ارتباط في بيانات السلسلة لا آلية بنيوية.", "A correlation in series data, not a structural mechanism."),
        difficulty: "intermediate",
      },
      {
        id: "q-l12-4",
        kind: "critique",
        prompt: L("نقد: QSAR بـ R² تدريب 0.95 بلا اختبار وبلا AD وبلا y-scrambling.", "Critique: QSAR with training R² 0.95, no test, no AD, no y-scrambling."),
        answer: "Curve fitting. Cannot claim prediction. Educational overfit pattern.",
        explanation: L("مطابقة منحنى لا تنبؤ. نمط حفظ تعليمي.", "Curve fitting, not prediction. Educational overfit pattern."),
        difficulty: "advanced",
      },
      {
        id: "q-l12-5",
        kind: "short",
        prompt: L("ماذا يفعل y-scrambling؟", "What does y-scrambling do?"),
        answer: "Shuffles activities and retrains; persistent high performance implies the model fits noise/leakage.",
        explanation: L("يخلط النشاط ويعيد التدريب؛ بقاء الأداء يعني حفظ ضجيج/تسريب.", "Shuffles activity and retrains; remaining performance means fitting noise/leakage."),
        difficulty: "advanced",
      },
      {
        id: "q-l12-6",
        kind: "mcq",
        prompt: L("محاذاة 3D-QSAR إذا أُسيئت:", "If 3D-QSAR alignment is wrong:"),
        options: [
          L("تبقى الخرائط كثافة إلكترونية صادقة.", "The maps remain true electron density."),
          L("يحفظ النموذج خطأً مقنعاً.", "The model memorises a convincing error."),
          L("تُلغى الحاجة للتحقّق الخارجي.", "External validation becomes unnecessary."),
          L("يصبح CoMFA تجربة NMR.", "CoMFA becomes an NMR experiment."),
        ],
        answer: 1,
        explanation: L("المحاذاة هي النموذج.", "The alignment is the model."),
        difficulty: "researcher",
      },
    ],
  },
  {
    id: "q-l13",
    title: L("خط الفرز", "The screening line"),
    description: L("كل سهم قرار.", "Every arrow is a decision."),
    lessonId: "l13-workflow",
    questions: [
      {
        id: "q-l13-1",
        kind: "tf",
        prompt: L("خط أطول بـ MD وMM/PBSA على كل المكتبة يزيد الحقيقة تلقائياً.", "A longer pipeline with MD and MM/PBSA on the whole library automatically increases truth."),
        answer: false,
        explanation: L("قد يزيد الثقة الزائفة. كل طبقة تحتاج قاعدة مرور.", "It may increase false confidence. Each layer needs a pass rule."),
        difficulty: "beginner",
      },
      {
        id: "q-l13-2",
        kind: "mcq",
        prompt: L("ZINC/ChEMBL/PubChem/DrugBank في هذه الأكاديمية:", "ZINC/ChEMBL/PubChem/DrugBank in this academy:"),
        options: [
          L("أرقام حجم أبدية محفوظة.", "Eternal memorised size numbers."),
          L("مصادر مفاهيمية يُتحقق من وصولها وترخيصها يوم العمل.", "Conceptual sources whose access and license are verified on the working day."),
          L("ملك عام بلا شروط.", "Unconditional public domain."),
          L("بدائل عن التجربة.", "Replacements for experiment."),
        ],
        answer: 1,
        explanation: L("المحتوى والشروط تتغيّر. لا تختلق أحجاماً.", "Content and terms change. Do not invent sizes."),
        difficulty: "intermediate",
      },
      {
        id: "q-l13-3",
        kind: "critique",
        prompt: L("نقد: شراء أفضل 50 درجة وكلها نفس الـ scaffold.", "Critique: buying the top 50 scores, all the same scaffold."),
        answer: "Assayed one chemotype 50 times. Cluster and take representatives.",
        explanation: L("فحصت كيمياء واحدة خمسين مرة. عنقود وممثلون.", "You assayed one chemistry fifty times. Cluster and take representatives."),
        difficulty: "intermediate",
      },
      {
        id: "q-l13-4",
        kind: "tf",
        prompt: L("Consensus scoring يُصلح فيزياء protonation الخاطئة سحرياً.", "Consensus scoring magically repairs wrong protonation physics."),
        answer: false,
        explanation: L("إن أخطأت كل الدوال فالإجماع على الخطأ.", "If every function is wrong, consensus agrees on the error."),
        difficulty: "beginner",
      },
      {
        id: "q-l13-5",
        kind: "short",
        prompt: L("اذكر عمودين غير الدرجة في جدول أولوية دفاعي.", "Name two non-score columns in a defensible priority table."),
        answer: "Pose hypothesis sentence; scaffold cluster; ADMET/PAINS flags; supply (any two).",
        explanation: L("جملة هيئة؛ عنقود scaffold؛ إنذارات ADMET؛ التوفر.", "Pose sentence; scaffold cluster; ADMET flags; supply."),
        difficulty: "advanced",
      },
    ],
  },
  {
    id: "q-l16",
    title: L("تعلّم آلي بلا سحر", "ML without magic"),
    description: L("بيانات → تمثيل → نموذج → تحقّق.", "Data → representation → model → validation."),
    lessonId: "l16-pipeline",
    questions: [
      {
        id: "q-l16-1",
        kind: "tf",
        prompt: L("شبكة على بيانات مسربة «تنجح» بسهولة وهذا يكفي للاكتشاف.", "A net on leaked data 'succeeds' easily and that is enough for discovery."),
        answer: false,
        explanation: L("تقيس الذاكرة. اطلب scaffold split وخط أساس تشابهي.", "It measures memory. Demand a scaffold split and a similarity baseline."),
        difficulty: "beginner",
      },
      {
        id: "q-l16-2",
        kind: "mcq",
        prompt: L("طية AlphaFold بالنسبة للفرز:", "An AlphaFold fold for screening:"),
        options: [
          L("مستقبِل جاهز دائماً.", "Always a docking-ready receptor."),
          L("فرضية بنيوية؛ الجيب قد يكون مغلقاً؛ pLDDT المنخفض إنذار.", "A structural hypothesis; the pocket may be closed; low pLDDT is an alarm."),
          L("تساوي co-crystal.", "Equals a co-crystal."),
          L("تقيس Kd.", "Measures Kd."),
        ],
        answer: 1,
        explanation: L("fold ≠ bound pose.", "A fold ≠ a bound pose."),
        difficulty: "intermediate",
      },
      {
        id: "q-l16-3",
        kind: "critique",
        prompt: L("نقد: 200 بنية مولَّدة نُشرت كمثبطات دون SA ودون فحص.", "Critique: 200 generated structures published as inhibitors with no SA and no assay."),
        answer: "An art gallery. Validity, makeability, and assay are the gates. Educational generative overclaim.",
        explanation: L("معرض رسوم. الصلاحية والصنع والفحص هي البوابات.", "An art gallery. Validity, makeability, and assay are the gates."),
        difficulty: "advanced",
      },
      {
        id: "q-l16-4",
        kind: "short",
        prompt: L("لماذا يبقى ECFP+XGBoost خط أساس إلزامي لورقة GNN؟", "Why is ECFP+XGBoost still a mandatory baseline in a GNN paper?"),
        answer: "If a classical fingerprint model wins on a hard split, the architecture did not earn its complexity.",
        explanation: L("إن فاز نموذج بصمات كلاسيكي على تقسيم قاسٍ فالعمارة لم تستحق تعقيدها.", "If a classical fingerprint model wins on a hard split, the architecture did not earn its complexity."),
        difficulty: "researcher",
      },
      {
        id: "q-l16-5",
        kind: "tf",
        prompt: L("دالة تقييم ML التي تفوز على نفس توزيع PDB تتعلم بالضرورة فيزياء الارتباط.", "An ML scoring function that wins on the same PDB distribution has necessarily learned binding physics."),
        answer: false,
        explanation: L("قد تتعلم scaffolds. اطلب pose decoys وأهدافاً محجوبة.", "It may learn scaffolds. Demand pose decoys and held-out targets."),
        difficulty: "advanced",
      },
      {
        id: "q-l16-6",
        kind: "mcq",
        prompt: L("ما يجعل ورقة ML علماً؟", "What makes an ML paper science?"),
        options: [
          L("AUC على split عشوائي فقط.", "AUC on a random split only."),
          L("سؤال محدد، خط أساس صعب، AD، معيار فشل، ويفضَّل جزيء فُحص.", "A specific question, hard baseline, AD, failure criterion, preferably an assayed molecule."),
          L("أكبر شبكة متاحة.", "The largest available net."),
          L("خطاب استبدال التجربة.", "Talk of replacing experiment."),
        ],
        answer: 1,
        explanation: L("القابلية للتفنيد والخطوط الأساس لا حجم النموذج.", "Falsifiability and baselines, not model size."),
        difficulty: "professor",
      },
    ],
  },
];

export {
  flashcards,
  mistakes,
  commands,
  equations,
  dictionary,
  vivaQuestions,
  comparisons,
  caseStudies,
  labs,
  graphNodes,
  graphEdges,
  challengeScenarios,
  papersOfWeek,
  dailyQuestions,
  frontierTopics,
} from "./knowledge-rest";

