/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBuilderRouteImport } from './routes/_app/builder'
import { Route as AppCalculatorsRouteImport } from './routes/_app/calculators'
import { Route as AppCasesRouteImport } from './routes/_app/cases'
import { Route as AppChallengeRouteImport } from './routes/_app/challenge'
import { Route as AppCommandsRouteImport } from './routes/_app/commands'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppDesignLabRouteImport } from './routes/_app/design-lab'
import { Route as AppDictionaryRouteImport } from './routes/_app/dictionary'
import { Route as AppEquationsRouteImport } from './routes/_app/equations'
import { Route as AppEthicsRouteImport } from './routes/_app/ethics'
import { Route as AppExamRouteImport } from './routes/_app/exam'
import { Route as AppFiguresRouteImport } from './routes/_app/figures'
import { Route as AppFlashcardsRouteImport } from './routes/_app/flashcards'
import { Route as AppFrontierRouteImport } from './routes/_app/frontier'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppMethodsRouteImport } from './routes/_app/methods'
import { Route as AppMistakesRouteImport } from './routes/_app/mistakes'
import { Route as AppNotebookRouteImport } from './routes/_app/notebook'
import { Route as AppPapersRouteImport } from './routes/_app/papers'
import { Route as AppPathsRouteImport } from './routes/_app/paths'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppPythonRouteImport } from './routes/_app/python'
import { Route as AppQuizzesRouteImport } from './routes/_app/quizzes'
import { Route as AppRoadmapRouteImport } from './routes/_app/roadmap'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppViewerRouteImport } from './routes/_app/viewer'
import { Route as AppVivaRouteImport } from './routes/_app/viva'
import { Route as AppLabsIndexRouteImport } from './routes/_app/labs/index'
import { Route as AppLabsLabIdRouteImport } from './routes/_app/labs/$labId'
import { Route as AppLearnLevelIdRouteImport } from './routes/_app/learn/$levelId'
import { Route as AppLessonLessonIdRouteImport } from './routes/_app/lesson/$lessonId'
import { Route as AppQuizQuizIdRouteImport } from './routes/_app/quiz/$quizId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorsRoute = AppCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeRoute = AppChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandsRoute = AppCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignLabRoute = AppDesignLabRouteImport.update({
  id: '/design-lab',
  path: '/design-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppDictionaryRoute = AppDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AppRoute,
} as any)
const AppEquationsRoute = AppEquationsRouteImport.update({
  id: '/equations',
  path: '/equations',
  getParentRoute: () => AppRoute,
} as any)
const AppEthicsRoute = AppEthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => AppRoute,
} as any)
const AppExamRoute = AppExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AppRoute,
} as any)
const AppFiguresRoute = AppFiguresRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppFrontierRoute = AppFrontierRouteImport.update({
  id: '/frontier',
  path: '/frontier',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodsRoute = AppMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookRoute = AppNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppPapersRoute = AppPapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPythonRoute = AppPythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppViewerRoute = AppViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => AppRoute,
} as any)
const AppVivaRoute = AppVivaRouteImport.update({
  id: '/viva',
  path: '/viva',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsIndexRoute = AppLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsLabIdRoute = AppLabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnLevelIdRoute = AppLearnLevelIdRouteImport.update({
  id: '/learn/$levelId',
  path: '/learn/$levelId',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonLessonIdRoute = AppLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizQuizIdRoute = AppQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/builder': typeof AppBuilderRoute
  '/calculators': typeof AppCalculatorsRoute
  '/cases': typeof AppCasesRoute
  '/challenge': typeof AppChallengeRoute
  '/commands': typeof AppCommandsRoute
  '/compare': typeof AppCompareRoute
  '/design-lab': typeof AppDesignLabRoute
  '/dictionary': typeof AppDictionaryRoute
  '/equations': typeof AppEquationsRoute
  '/ethics': typeof AppEthicsRoute
  '/exam': typeof AppExamRoute
  '/figures': typeof AppFiguresRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/frontier': typeof AppFrontierRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/methods': typeof AppMethodsRoute
  '/mistakes': typeof AppMistakesRoute
  '/notebook': typeof AppNotebookRoute
  '/papers': typeof AppPapersRoute
  '/paths': typeof AppPathsRoute
  '/projects': typeof AppProjectsRoute
  '/python': typeof AppPythonRoute
  '/quizzes': typeof AppQuizzesRoute
  '/roadmap': typeof AppRoadmapRoute
  '/search': typeof AppSearchRoute
  '/skills': typeof AppSkillsRoute
  '/stats': typeof AppStatsRoute
  '/viewer': typeof AppViewerRoute
  '/viva': typeof AppVivaRoute
  '/labs/$labId': typeof AppLabsLabIdRoute
  '/learn/$levelId': typeof AppLearnLevelIdRoute
  '/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/labs/': typeof AppLabsIndexRoute
}
export interface FileRoutesByTo {
  '/builder': typeof AppBuilderRoute
  '/calculators': typeof AppCalculatorsRoute
  '/cases': typeof AppCasesRoute
  '/challenge': typeof AppChallengeRoute
  '/commands': typeof AppCommandsRoute
  '/compare': typeof AppCompareRoute
  '/design-lab': typeof AppDesignLabRoute
  '/dictionary': typeof AppDictionaryRoute
  '/equations': typeof AppEquationsRoute
  '/ethics': typeof AppEthicsRoute
  '/exam': typeof AppExamRoute
  '/figures': typeof AppFiguresRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/frontier': typeof AppFrontierRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/methods': typeof AppMethodsRoute
  '/mistakes': typeof AppMistakesRoute
  '/notebook': typeof AppNotebookRoute
  '/papers': typeof AppPapersRoute
  '/paths': typeof AppPathsRoute
  '/projects': typeof AppProjectsRoute
  '/python': typeof AppPythonRoute
  '/quizzes': typeof AppQuizzesRoute
  '/roadmap': typeof AppRoadmapRoute
  '/search': typeof AppSearchRoute
  '/skills': typeof AppSkillsRoute
  '/stats': typeof AppStatsRoute
  '/viewer': typeof AppViewerRoute
  '/viva': typeof AppVivaRoute
  '/': typeof AppIndexRoute
  '/labs/$labId': typeof AppLabsLabIdRoute
  '/learn/$levelId': typeof AppLearnLevelIdRoute
  '/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/labs': typeof AppLabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/builder': typeof AppBuilderRoute
  '/_app/calculators': typeof AppCalculatorsRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/challenge': typeof AppChallengeRoute
  '/_app/commands': typeof AppCommandsRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/design-lab': typeof AppDesignLabRoute
  '/_app/dictionary': typeof AppDictionaryRoute
  '/_app/equations': typeof AppEquationsRoute
  '/_app/ethics': typeof AppEthicsRoute
  '/_app/exam': typeof AppExamRoute
  '/_app/figures': typeof AppFiguresRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/frontier': typeof AppFrontierRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/methods': typeof AppMethodsRoute
  '/_app/mistakes': typeof AppMistakesRoute
  '/_app/notebook': typeof AppNotebookRoute
  '/_app/papers': typeof AppPapersRoute
  '/_app/paths': typeof AppPathsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/python': typeof AppPythonRoute
  '/_app/quizzes': typeof AppQuizzesRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/viewer': typeof AppViewerRoute
  '/_app/viva': typeof AppVivaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/labs/$labId': typeof AppLabsLabIdRoute
  '/_app/learn/$levelId': typeof AppLearnLevelIdRoute
  '/_app/lesson/$lessonId': typeof AppLessonLessonIdRoute
  '/_app/quiz/$quizId': typeof AppQuizQuizIdRoute
  '/_app/labs/': typeof AppLabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/calculators'
    | '/cases'
    | '/challenge'
    | '/commands'
    | '/compare'
    | '/design-lab'
    | '/dictionary'
    | '/equations'
    | '/ethics'
    | '/exam'
    | '/figures'
    | '/flashcards'
    | '/frontier'
    | '/knowledge'
    | '/methods'
    | '/mistakes'
    | '/notebook'
    | '/papers'
    | '/paths'
    | '/projects'
    | '/python'
    | '/quizzes'
    | '/roadmap'
    | '/search'
    | '/skills'
    | '/stats'
    | '/viewer'
    | '/viva'
    | '/labs/$labId'
    | '/learn/$levelId'
    | '/lesson/$lessonId'
    | '/quiz/$quizId'
    | '/labs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/builder'
    | '/calculators'
    | '/cases'
    | '/challenge'
    | '/commands'
    | '/compare'
    | '/design-lab'
    | '/dictionary'
    | '/equations'
    | '/ethics'
    | '/exam'
    | '/figures'
    | '/flashcards'
    | '/frontier'
    | '/knowledge'
    | '/methods'
    | '/mistakes'
    | '/notebook'
    | '/papers'
    | '/paths'
    | '/projects'
    | '/python'
    | '/quizzes'
    | '/roadmap'
    | '/search'
    | '/skills'
    | '/stats'
    | '/viewer'
    | '/viva'
    | '/'
    | '/labs/$labId'
    | '/learn/$levelId'
    | '/lesson/$lessonId'
    | '/quiz/$quizId'
    | '/labs'
  id:
    | '__root__'
    | '/_app'
    | '/_app/builder'
    | '/_app/calculators'
    | '/_app/cases'
    | '/_app/challenge'
    | '/_app/commands'
    | '/_app/compare'
    | '/_app/design-lab'
    | '/_app/dictionary'
    | '/_app/equations'
    | '/_app/ethics'
    | '/_app/exam'
    | '/_app/figures'
    | '/_app/flashcards'
    | '/_app/frontier'
    | '/_app/knowledge'
    | '/_app/methods'
    | '/_app/mistakes'
    | '/_app/notebook'
    | '/_app/papers'
    | '/_app/paths'
    | '/_app/projects'
    | '/_app/python'
    | '/_app/quizzes'
    | '/_app/roadmap'
    | '/_app/search'
    | '/_app/skills'
    | '/_app/stats'
    | '/_app/viewer'
    | '/_app/viva'
    | '/_app/'
    | '/_app/labs/$labId'
    | '/_app/learn/$levelId'
    | '/_app/lesson/$lessonId'
    | '/_app/quiz/$quizId'
    | '/_app/labs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builder': {
      id: '/_app/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculators': {
      id: '/_app/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof AppCalculatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge': {
      id: '/_app/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AppChallengeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commands': {
      id: '/_app/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AppCommandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-lab': {
      id: '/_app/design-lab'
      path: '/design-lab'
      fullPath: '/design-lab'
      preLoaderRoute: typeof AppDesignLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dictionary': {
      id: '/_app/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AppDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equations': {
      id: '/_app/equations'
      path: '/equations'
      fullPath: '/equations'
      preLoaderRoute: typeof AppEquationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ethics': {
      id: '/_app/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof AppEthicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam': {
      id: '/_app/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AppExamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/figures': {
      id: '/_app/figures'
      path: '/figures'
      fullPath: '/figures'
      preLoaderRoute: typeof AppFiguresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/frontier': {
      id: '/_app/frontier'
      path: '/frontier'
      fullPath: '/frontier'
      preLoaderRoute: typeof AppFrontierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/methods': {
      id: '/_app/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof AppMethodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes': {
      id: '/_app/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notebook': {
      id: '/_app/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AppNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/papers': {
      id: '/_app/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof AppPapersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paths': {
      id: '/_app/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/python': {
      id: '/_app/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof AppPythonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes': {
      id: '/_app/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viewer': {
      id: '/_app/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof AppViewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/viva': {
      id: '/_app/viva'
      path: '/viva'
      fullPath: '/viva'
      preLoaderRoute: typeof AppVivaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labs/': {
      id: '/_app/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AppLabsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labs/$labId': {
      id: '/_app/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof AppLabsLabIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/$levelId': {
      id: '/_app/learn/$levelId'
      path: '/learn/$levelId'
      fullPath: '/learn/$levelId'
      preLoaderRoute: typeof AppLearnLevelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson/$lessonId': {
      id: '/_app/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AppLessonLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz/$quizId': {
      id: '/_app/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AppQuizQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppCalculatorsRoute: typeof AppCalculatorsRoute
  AppCasesRoute: typeof AppCasesRoute
  AppChallengeRoute: typeof AppChallengeRoute
  AppCommandsRoute: typeof AppCommandsRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDesignLabRoute: typeof AppDesignLabRoute
  AppDictionaryRoute: typeof AppDictionaryRoute
  AppEquationsRoute: typeof AppEquationsRoute
  AppEthicsRoute: typeof AppEthicsRoute
  AppExamRoute: typeof AppExamRoute
  AppFiguresRoute: typeof AppFiguresRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppFrontierRoute: typeof AppFrontierRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMethodsRoute: typeof AppMethodsRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppNotebookRoute: typeof AppNotebookRoute
  AppPapersRoute: typeof AppPapersRoute
  AppPathsRoute: typeof AppPathsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppPythonRoute: typeof AppPythonRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppViewerRoute: typeof AppViewerRoute
  AppVivaRoute: typeof AppVivaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLabsLabIdRoute: typeof AppLabsLabIdRoute
  AppLearnLevelIdRoute: typeof AppLearnLevelIdRoute
  AppLessonLessonIdRoute: typeof AppLessonLessonIdRoute
  AppQuizQuizIdRoute: typeof AppQuizQuizIdRoute
  AppLabsIndexRoute: typeof AppLabsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppCalculatorsRoute: AppCalculatorsRoute,
  AppCasesRoute: AppCasesRoute,
  AppChallengeRoute: AppChallengeRoute,
  AppCommandsRoute: AppCommandsRoute,
  AppCompareRoute: AppCompareRoute,
  AppDesignLabRoute: AppDesignLabRoute,
  AppDictionaryRoute: AppDictionaryRoute,
  AppEquationsRoute: AppEquationsRoute,
  AppEthicsRoute: AppEthicsRoute,
  AppExamRoute: AppExamRoute,
  AppFiguresRoute: AppFiguresRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppFrontierRoute: AppFrontierRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMethodsRoute: AppMethodsRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppNotebookRoute: AppNotebookRoute,
  AppPapersRoute: AppPapersRoute,
  AppPathsRoute: AppPathsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppPythonRoute: AppPythonRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSearchRoute: AppSearchRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppStatsRoute: AppStatsRoute,
  AppViewerRoute: AppViewerRoute,
  AppVivaRoute: AppVivaRoute,
  AppIndexRoute: AppIndexRoute,
  AppLabsLabIdRoute: AppLabsLabIdRoute,
  AppLearnLevelIdRoute: AppLearnLevelIdRoute,
  AppLessonLessonIdRoute: AppLessonLessonIdRoute,
  AppQuizQuizIdRoute: AppQuizQuizIdRoute,
  AppLabsIndexRoute: AppLabsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
